/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.spark.sql.comet.execution.shuffle

import java.io.{EOFException, InputStream}
import java.nio.{ByteBuffer, ByteOrder}
import java.nio.channels.{Channels, ReadableByteChannel}

import scala.util.control.NonFatal

import org.apache.spark.sql.execution.metric.SQLMetric
import org.apache.spark.sql.vectorized.ColumnarBatch

import org.apache.comet.{CometShuffleReadFailureHandler, Native}
import org.apache.comet.vector.NativeUtil

/**
 * This iterator wraps a Spark input stream that is reading shuffle blocks generated by the Comet
 * native ShuffleWriterExec and then calls native code to decompress and decode the shuffle blocks
 * and use Arrow FFI to return the Arrow record batch.
 */
case class NativeBatchDecoderIterator(
    in: InputStream,
    decodeTime: SQLMetric,
    nativeLib: Native,
    nativeUtil: NativeUtil,
    tracingEnabled: Boolean,
    expectedSchema: Option[Array[Byte]] = None,
    dataBuffer: ShuffleBlockBuffer = new ShuffleBlockBuffer())
    extends Iterator[ColumnarBatch] {

  // One consumer reads this iterator, while task completion may close it from another thread.
  // The monitor protects decoder and batch ownership; transport reads stay outside it.
  private var isClosed = false
  private val longBuf = ByteBuffer.allocate(8).order(ByteOrder.LITTLE_ENDIAN)
  private var currentBatch: ColumnarBatch = null
  private var batch: Option[ColumnarBatch] = None
  private val validateRemoteFrames = in.isInstanceOf[CometShuffleReadFailureHandler]
  private var remoteDecoderHandle = 0L

  require(
    !validateRemoteFrames || expectedSchema.exists(_ != null),
    "Remote shuffle decoding requires the expected Spark schema")

  private val channel: ReadableByteChannel = if (in != null) {
    Channels.newChannel(in)
  } else {
    null
  }

  override def hasNext: Boolean = {
    synchronized {
      if (channel == null || isClosed) {
        return false
      }
      if (batch.isDefined) {
        return true
      }

      // Clear ownership before cleanup so a failed close cannot release this batch twice.
      if (currentBatch != null) {
        val previous = currentBatch
        currentBatch = null
        previous.close()
      }
    }

    fetchNext()
  }

  def next(): ColumnarBatch = {
    if (!hasNext) {
      throw new NoSuchElementException
    }

    synchronized {
      // Completion may have closed the iterator after hasNext() returned.
      if (isClosed) {
        throw new NoSuchElementException
      }
      currentBatch = batch.get
      batch = None
      currentBatch
    }
  }

  private def fetchNext(): Boolean = {
    // The remote input owns metadata, transport, and frame-boundary failure classification. Do
    // not turn deliberately unreported metadata timeouts or stream-close failures into corruption.
    // Read outside the monitor so close() can unblock the underlying stream.
    val block = readNextBlock()
    var nativeFailure: Throwable = null
    try {
      synchronized {
        // Cleanup may have finished during the read. Do not create a decoder or import a batch
        // after close(), and publish each decoded batch before cleanup can inspect ownership.
        if (isClosed) {
          return false
        }
        batch = block.flatMap { case (fieldCount, dataBuf, bytesToRead) =>
          val startTime = System.nanoTime()
          // Invalid expected schemas are setup failures, not evidence of corrupt persisted data.
          if (validateRemoteFrames && remoteDecoderHandle == 0L) {
            remoteDecoderHandle = nativeLib.createRemoteShuffleDecoder(expectedSchema.get)
          }
          val decoded = nativeUtil.getNextBatch(
            fieldCount,
            (arrayAddrs, schemaAddrs) => {
              try {
                if (validateRemoteFrames) {
                  nativeLib.decodeShuffleBlockWithValidation(
                    dataBuf,
                    bytesToRead,
                    arrayAddrs,
                    schemaAddrs,
                    tracingEnabled,
                    remoteDecoderHandle)
                } else {
                  nativeLib.decodeShuffleBlock(
                    dataBuf,
                    bytesToRead,
                    arrayAddrs,
                    schemaAddrs,
                    tracingEnabled)
                }
              } catch {
                case NonFatal(failure) =>
                  // Record only native decode failures; creation, allocation and import failures
                  // must not be reported as corrupt remote data. Let NativeUtil clean up first.
                  nativeFailure = failure
                  throw failure
              }
            })
          decodeTime.add(System.nanoTime() - startTime)
          decoded
        }
        if (batch.isEmpty) {
          close()
        }
        batch.isDefined
      }
    } catch {
      case NonFatal(failure) if failure eq nativeFailure =>
        // Reporting can make an RPC. It must run after Arrow cleanup and outside the monitor so
        // task completion can release the decoder while that reporting is in progress.
        in match {
          case handler: CometShuffleReadFailureHandler => handler.onShuffleReadFailure(failure)
          case _ =>
        }
        throw failure
    }
  }

  private def readNextBlock(): Option[(Int, ByteBuffer, Int)] = {
    // read compressed batch size from header
    longBuf.clear()
    while (longBuf.hasRemaining && channel.read(longBuf) >= 0) {}

    // If we reach the end of the stream, we are done, or if we read partial length
    // then the stream is corrupted.
    if (longBuf.hasRemaining) {
      if (longBuf.position() == 0) {
        return None
      }
      throw new EOFException("Data corrupt: unexpected EOF while reading compressed ipc lengths")
    }

    // get compressed length (including headers)
    longBuf.flip()
    val compressedLength = longBuf.getLong

    // read field count from header
    longBuf.clear()
    while (longBuf.hasRemaining && channel.read(longBuf) >= 0) {}
    if (longBuf.hasRemaining) {
      throw new EOFException("Data corrupt: unexpected EOF while reading field count")
    }
    longBuf.flip()
    val fieldCount = longBuf.getLong.toInt

    // read body
    val bytesToRead = compressedLength - 8
    if (bytesToRead > Integer.MAX_VALUE) {
      // very unlikely that shuffle block will reach 2GB
      throw new IllegalStateException(
        s"Native shuffle block size of $bytesToRead exceeds " +
          s"maximum of ${Integer.MAX_VALUE}. Try reducing shuffle batch size.")
    }
    val dataBuf = dataBuffer.acquire(bytesToRead.toInt)
    while (dataBuf.hasRemaining && channel.read(dataBuf) >= 0) {}
    if (dataBuf.hasRemaining) {
      throw new EOFException("Data corrupt: unexpected EOF while reading compressed batch")
    }

    Some((fieldCount, dataBuf, bytesToRead.toInt))
  }

  def close(): Unit = {
    synchronized {
      if (!isClosed) {
        // hasNext() owns a decoded batch even before next() exposes it to the consumer. Release
        // that lookahead on early task completion as well as the last batch returned by next().
        // Clear ownership before cleanup so a failing close remains idempotent.
        isClosed = true
        val previous = currentBatch
        currentBatch = null
        val prefetched = batch
        batch = None
        val decoderHandle = remoteDecoderHandle
        remoteDecoderHandle = 0L

        var failure: Throwable = null
        def release(resource: => Unit): Unit = {
          try resource
          catch {
            case caught: Throwable =>
              if (failure == null) failure = caught
              else if (caught ne failure) failure.addSuppressed(caught)
          }
        }

        if (previous != null) release(previous.close())
        prefetched.filterNot(_ eq previous).foreach(pending => release(pending.close()))
        if (decoderHandle != 0L) release(nativeLib.releaseRemoteShuffleDecoder(decoderHandle))
        if (in != null) release(in.close())
        if (failure != null) throw failure
      }
    }
  }
}

/**
 * The direct buffer a compressed shuffle block is read into before it is handed to native code.
 *
 * One instance is meant to live for a whole reduce task and be shared by every
 * [[NativeBatchDecoderIterator]] the task creates: the block-store reader creates one iterator
 * per fetched map output, and a reducer over thousands of map outputs would otherwise allocate a
 * fresh direct buffer per map output. The buffer only grows, to twice the largest block seen, and
 * is released with the task. This mirrors the direct-read path's `CometShuffleBlockIterator`,
 * which keeps one buffer per task for the same reason.
 *
 * Not thread-safe: a block is read into the buffer and decoded from it by the same thread before
 * the next block is read.
 */
final class ShuffleBlockBuffer {
  import ShuffleBlockBuffer._

  private var buffer: ByteBuffer = _

  /** Number of direct buffers allocated so far; exposed for tests. */
  private[shuffle] var allocations = 0

  /**
   * Returns a buffer positioned at zero with its limit set to `bytesToRead`, growing the
   * underlying allocation when the block does not fit.
   */
  def acquire(bytesToRead: Int): ByteBuffer = {
    if (buffer == null || buffer.capacity() < bytesToRead) {
      // Doubling keeps the number of reallocations logarithmic in the largest block. Clamp so a
      // block near the 2 GB direct-buffer limit still gets a buffer it fits in.
      val newCapacity =
        (bytesToRead * 2L).max(INITIAL_BUFFER_SIZE).min(Integer.MAX_VALUE).toInt
      buffer = ByteBuffer.allocateDirect(newCapacity)
      allocations += 1
    }
    buffer.clear()
    buffer.limit(bytesToRead)
    buffer
  }
}

object ShuffleBlockBuffer {
  private val INITIAL_BUFFER_SIZE = 128 * 1024
}
