/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * In Apache Hadoop this header is generated by CMake and defines the feature
 * probes libhdfs compiles against, chiefly HAVE_BETTER_TLS. jni_helper.c
 * includes it unconditionally, so it has to exist. Leaving every probe undefined
 * selects the portable pthread_getspecific path in os/thread_local_storage.h,
 * which is what this crate wants and what the upstream hdfs-sys crate also
 * shipped (as a zero-byte file).
 */
