#!/bin/bash
# Deploy cometbot to a remote host
#
# Required environment variables:
#   COMETBOT_DEPLOY_HOST    - Remote hostname
#   COMETBOT_DEPLOY_USER    - Remote SSH username
#   COMETBOT_DEPLOY_DIR     - Remote installation directory (e.g., /home/user/cometbot)
#
# Optional environment variables:
#   COMETBOT_GITHUB_TOKEN  - GitHub token for API access
#   COMETBOT_SLACK_TOKEN         - Slack bot token for notifications
#   COMETBOT_SLACK_CHANNEL           - Slack channel for notifications
#
# Prerequisites on remote host:
#   - Python 3.10+
#   - pip
#   - kubectl (configured with cluster access)
#   - docker

set -e

# Required configuration - fail if not set
: "${COMETBOT_DEPLOY_HOST:?Error: COMETBOT_DEPLOY_HOST environment variable is required}"
: "${COMETBOT_DEPLOY_USER:?Error: COMETBOT_DEPLOY_USER environment variable is required}"
: "${COMETBOT_DEPLOY_DIR:?Error: COMETBOT_DEPLOY_DIR environment variable is required}"

REMOTE_HOST="$COMETBOT_DEPLOY_HOST"
REMOTE_USER="$COMETBOT_DEPLOY_USER"
REMOTE_DIR="$COMETBOT_DEPLOY_DIR"
GITHUB_TOKEN="${COMETBOT_GITHUB_TOKEN:-}"
SLACK_TOKEN="${COMETBOT_SLACK_TOKEN:-}"
SLACK_CH="${COMETBOT_SLACK_CHANNEL:-}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Deploying cometbot to ${REMOTE_HOST} ===${NC}"

# Get the directory of this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Generate build timestamp
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
echo -e "${YELLOW}Build timestamp: ${BUILD_TIMESTAMP}${NC}"

# Write build info to package
cat > "$PROJECT_DIR/src/cometbot/_build_info.py" << PYEOF
# Auto-generated by deploy script - do not edit
BUILD_TIMESTAMP = "${BUILD_TIMESTAMP}"
PYEOF

# Build the wheel
echo -e "${YELLOW}Building wheel...${NC}"
cd "$PROJECT_DIR"
rm -rf dist/  # Clean old wheels
uv build --wheel --out-dir dist

# Find the wheel file
WHEEL=$(ls -t dist/cometbot-*.whl | head -1)
if [ -z "$WHEEL" ]; then
    echo -e "${RED}Error: No wheel file found${NC}"
    exit 1
fi
echo -e "${GREEN}Built: ${WHEEL}${NC}"

# Copy files to remote host
echo -e "${YELLOW}Copying files to ${REMOTE_HOST}...${NC}"
ssh "${REMOTE_USER}@${REMOTE_HOST}" "mkdir -p ${REMOTE_DIR}/k8s"
scp "$WHEEL" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/"

# Copy Dockerfile and k8s templates
scp "$PROJECT_DIR/Dockerfile" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/"
scp "$PROJECT_DIR/k8s/"*.yaml "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/k8s/"
scp "$PROJECT_DIR/authorized_users.txt" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/"

# Build Docker image on remote host
echo -e "${YELLOW}Building Docker image on ${REMOTE_HOST}...${NC}"
ssh "${REMOTE_USER}@${REMOTE_HOST}" bash <<EOF
set -e
cd ${REMOTE_DIR}
REGISTRY=\${COMETBOT_REGISTRY:-localhost:5000}
echo "Building Comet Docker image (registry: \$REGISTRY)..."
docker build -t comet-benchmark-automation:latest -t \$REGISTRY/comet-benchmark-automation:latest .
docker push \$REGISTRY/comet-benchmark-automation:latest
echo "Comet image built and pushed."
EOF

# Install on remote host
echo -e "${YELLOW}Installing on ${REMOTE_HOST}...${NC}"
ssh "${REMOTE_USER}@${REMOTE_HOST}" bash <<EOF
set -e
cd ${REMOTE_DIR}

# Create virtual environment if it doesn't exist
if [ ! -d venv ]; then
    echo "Creating virtual environment..."
    python3 -m venv venv
fi

# Activate and install
source venv/bin/activate
pip install --upgrade pip
pip install --force-reinstall --no-cache-dir ${REMOTE_DIR}/$(basename $WHEEL)

# Verify installation
cometbot --help > /dev/null
echo "cometbot installed successfully"
EOF

# Set up systemd service
echo -e "${YELLOW}Setting up systemd service...${NC}"
ssh "${REMOTE_USER}@${REMOTE_HOST}" bash <<EOF
set -e

# Generate systemd service file from deployment config
cat > ${REMOTE_DIR}/cometbot.service <<SVCEOF
[Unit]
Description=cometbot GitHub Bot - monitors PRs for benchmark requests
After=network.target docker.service
Wants=docker.service

[Service]
Type=simple
User=${REMOTE_USER}
WorkingDirectory=${REMOTE_DIR}
Environment="PATH=${REMOTE_DIR}/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/snap/bin"
Environment="COMETBOT_PROJECT_DIR=${REMOTE_DIR}"
EnvironmentFile=-${REMOTE_DIR}/env
ExecStart=${REMOTE_DIR}/venv/bin/cometbot bot start
Restart=always
RestartSec=30

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=cometbot

[Install]
WantedBy=multi-user.target
SVCEOF

# Create env file if it doesn't exist
if [ ! -f ${REMOTE_DIR}/env ]; then
    echo "Creating env file..."
    cat > ${REMOTE_DIR}/env <<'ENVEOF'
COMETBOT_GITHUB_TOKEN=
COMETBOT_REGISTRY=localhost:5000
COMETBOT_SLACK_TOKEN=
COMETBOT_SLACK_CHANNEL=
ENVEOF
    chmod 600 ${REMOTE_DIR}/env
fi

# Update the env file with tokens if provided
if [ -n "${GITHUB_TOKEN}" ]; then
    sed -i "s|^COMETBOT_GITHUB_TOKEN=.*|COMETBOT_GITHUB_TOKEN=${GITHUB_TOKEN}|" ${REMOTE_DIR}/env
fi
if [ -n "${SLACK_TOKEN}" ]; then
    sed -i "s|^COMETBOT_SLACK_TOKEN=.*|COMETBOT_SLACK_TOKEN=${SLACK_TOKEN}|" ${REMOTE_DIR}/env
fi
if [ -n "${SLACK_CH}" ]; then
    sed -i "s|^COMETBOT_SLACK_CHANNEL=.*|COMETBOT_SLACK_CHANNEL=${SLACK_CH}|" ${REMOTE_DIR}/env
fi

# Install the service (requires sudo)
sudo cp ${REMOTE_DIR}/cometbot.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable cometbot

echo "Service installed. To start: sudo systemctl start cometbot"
echo "To check status: sudo systemctl status cometbot"
echo "To view logs: sudo journalctl -u cometbot -f"
EOF

# Restart the bot and tail logs
echo -e "${YELLOW}Restarting cometbot service...${NC}"
ssh "${REMOTE_USER}@${REMOTE_HOST}" "sudo systemctl restart cometbot"
echo -e "${GREEN}=== Deployment complete, tailing logs (Ctrl-C to stop) ===${NC}"
ssh "${REMOTE_USER}@${REMOTE_HOST}" "sudo journalctl -u cometbot -f"
