FROM docker-upstream.apple.com/centos:centos7.9.2009

USER root

# Install Rust toolchain
RUN yum -y update
RUN yum -y install epel-release
RUN yum -y install \
    kernel-devel \
    make \
    curl \
    xz \
    python36 \
    patch \
    openssl-devel \
    autoconf \
    libtool \
    automake \
    autotools-dev \
    byacc \
    flex \
    cmake3 \
    wget \
    python-devel \
    git \
    neon-devel \
    jq \
    perl-Digest-SHA

# Import certificates
RUN curl -k https://pages.github.pie.apple.com/crypto-services/trust-apple-corp-root-cas/trust_apple_corp_root_cas.sh | bash 2>&1 > /dev/null

# Install AppleJDK, see https://java.apple.com/downloads/applejdk-11.html#installation-with-linux-package-manager
RUN rpm --import https://java.apple.com/applejdk/RPM-GPG-KEY-AppleJDK
RUN curl -o /etc/yum.repos.d/AppleJDK.repo https://java.apple.com/applejdk/AppleJDK.repo
RUN yum -y update
RUN yum -y install applejdk-11
ENV JAVA_HOME="/usr/lib/jvm/applejdk-11"
ENV PATH="$JAVA_HOME/bin:${PATH}"

# Install rustup
RUN cd /tmp && curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install cargo2junit
RUN rustup install nightly && cargo +nightly install cargo2junit

# Use Rust toolchain, and seed Rust
COPY rust-toolchain  /rust-toolchain
RUN cargo search

# llvm-toolset-7-clang is too old (clang 5) which cannot work with latest MacOSX sdk.
RUN yum -y install https://kickstart.pie.apple.com/reposync/el7-x86_64/centos-7.9.2009-extras/Packages/centos-release-scl-rh-2-3.el7.centos.noarch.rpm
RUN yum -y install devtoolset-8-gcc-c++

# The default cmake is too old, so replace it with cmake3
RUN ln -s /usr/bin/cmake3 /usr/bin/cmake

# Build and install libxml
RUN cd / && wget https://github.com/GNOME/libxml2/archive/refs/tags/v2.9.10.tar.gz && tar xfvz v2.9.10.tar.gz && rm v2.9.10.tar.gz \
    && cd /libxml2-2.9.10 \
    && scl enable devtoolset-8 "sh ./autogen.sh && make && make install" \
    && rm -rf /libxml2-2.9.10
ENV PATH="/usr/local/bin/:${PATH}"

ENTRYPOINT ["/bin/bash"]
