FROM docker.apple.com/pie/comet-builder:stage2

# Build OSXCross
# To packaging MacOSX sdk on a local Mac with Xcode installed:
#   1. checkout OSXCross repo, i.e. git clone https://github.com/tpoechtrager/osxcross.git
#   2. run the script to packing sdk tarballs: cd osxcross; ./tools/gen_sdk_package.sh
RUN cd / && git clone --depth 1 https://github.com/tpoechtrager/osxcross.git \
    && cd /osxcross/tarballs \
    && wget https://artifacts.apple.com/artifactory/amp-binaries-local/org/apache/spark/MacOSX12.3.sdk.tar.xz \
    && cd /osxcross \
    && scl enable devtoolset-8 "UNATTENDED=1 ./build.sh"
ENV PATH="/osxcross/target/bin:${PATH}"

# Use osxcross toolchain for cargo
COPY dev/cargo.config /root/.cargo/config

ENTRYPOINT ["/bin/bash"]
