// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! Spark's `PivotFirst` aggregate. Used only by the second phase of the optimized pivot plan
//! generated by `PivotTransformer`. For each group, `PivotFirst` maintains an array of
//! `pivot_values.len()` slots; on each input row it evaluates the pivot column, looks up its
//! index in `pivot_values`, and writes the value column into that slot when a match is found
//! and the value is non-null. Rows with unmatched pivot values are ignored; matched rows with
//! a null value column leave the slot unchanged (matches Spark).
//!
//! State layout is one column per pivot slot, matching Spark's `aggBufferAttributes` (which
//! declares `indexSize` `AttributeReference`s, one per pivot value). This keeps the shuffle
//! schema between Partial and Final consistent with what Spark catalyst declared — otherwise
//! the shuffle exchange rejects the batch. `evaluate()` reassembles the slots into a
//! `ListArray` matching `PivotFirst.dataType = ArrayType(value_type)`.

use arrow::array::{Array, ArrayRef};
use arrow::datatypes::{DataType, Field, FieldRef};
use datafusion::common::utils::SingleRowListArrayBuilder;
use datafusion::common::{DataFusionError, Result as DFResult, ScalarValue};
use datafusion::logical_expr::function::{AccumulatorArgs, StateFieldsArgs};
use datafusion::logical_expr::Volatility::Immutable;
use datafusion::logical_expr::{Accumulator, AggregateUDFImpl, Signature};
use std::collections::HashMap;
use std::sync::Arc;

/// UDAF implementation of Spark's `PivotFirst`.
///
/// `pivot_values` is a fixed, plan-time list of the pivot column values that occupy each
/// output slot; `pivot_index[v] = i` means an input row whose pivot column equals `v` writes
/// into slot `i`.
#[derive(Debug)]
pub struct SparkPivotFirst {
    signature: Signature,
    value_type: DataType,
    pivot_values: Vec<ScalarValue>,
    pivot_index: HashMap<ScalarValue, usize>,
}

impl PartialEq for SparkPivotFirst {
    fn eq(&self, other: &Self) -> bool {
        self.value_type == other.value_type && self.pivot_values == other.pivot_values
    }
}

impl Eq for SparkPivotFirst {}

impl std::hash::Hash for SparkPivotFirst {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.value_type.hash(state);
        self.pivot_values.hash(state);
    }
}

impl SparkPivotFirst {
    pub fn new(value_type: DataType, pivot_values: Vec<ScalarValue>) -> Self {
        let mut pivot_index = HashMap::with_capacity(pivot_values.len());
        // Spark's PivotFirst uses the FIRST occurrence's index (HashMap/TreeMap semantics), so
        // when duplicates are somehow present we mirror that by only inserting the first one.
        for (i, v) in pivot_values.iter().enumerate() {
            pivot_index.entry(v.clone()).or_insert(i);
        }
        Self {
            signature: Signature::user_defined(Immutable),
            value_type,
            pivot_values,
            pivot_index,
        }
    }
}

impl AggregateUDFImpl for SparkPivotFirst {
    fn name(&self) -> &str {
        "pivot_first"
    }

    fn signature(&self) -> &Signature {
        &self.signature
    }

    fn return_type(&self, _arg_types: &[DataType]) -> DFResult<DataType> {
        Ok(DataType::List(Arc::new(Field::new_list_field(
            self.value_type.clone(),
            true,
        ))))
    }

    fn state_fields(&self, args: StateFieldsArgs) -> DFResult<Vec<FieldRef>> {
        // One field per pivot slot, matching Spark's aggBufferAttributes so the shuffle
        // exchange sees the same schema catalyst declared.
        Ok(self
            .pivot_values
            .iter()
            .enumerate()
            .map(|(i, _)| {
                Arc::new(Field::new(
                    format!("{}[{}]", args.name, i),
                    self.value_type.clone(),
                    true,
                ))
            })
            .collect())
    }

    fn accumulator(&self, _acc_args: AccumulatorArgs) -> DFResult<Box<dyn Accumulator>> {
        Ok(Box::new(PivotFirstAccumulator::new(
            self.value_type.clone(),
            self.pivot_values.clone(),
            self.pivot_index.clone(),
        )))
    }
}

/// Per-group state: `slots[i]` holds the latest non-null value assigned to pivot slot `i`, or
/// `None` when nothing has written to that slot yet.
#[derive(Debug)]
struct PivotFirstAccumulator {
    value_type: DataType,
    pivot_index: HashMap<ScalarValue, usize>,
    slots: Vec<Option<ScalarValue>>,
}

impl PivotFirstAccumulator {
    fn new(
        value_type: DataType,
        pivot_values: Vec<ScalarValue>,
        pivot_index: HashMap<ScalarValue, usize>,
    ) -> Self {
        let slots = vec![None; pivot_values.len()];
        Self {
            value_type,
            pivot_index,
            slots,
        }
    }

    /// Turn slot `i` into a `ScalarValue`, substituting a typed null when the slot is empty.
    fn slot_or_null(&self, i: usize) -> DFResult<ScalarValue> {
        Ok(match &self.slots[i] {
            Some(v) => v.clone(),
            None => ScalarValue::try_from(&self.value_type)?,
        })
    }
}

impl Accumulator for PivotFirstAccumulator {
    fn update_batch(&mut self, values: &[ArrayRef]) -> DFResult<()> {
        if values.len() != 2 {
            return Err(DataFusionError::Internal(format!(
                "PivotFirst expects 2 inputs (pivot, value); got {}",
                values.len()
            )));
        }
        let pivot_arr = &values[0];
        let value_arr = &values[1];
        if pivot_arr.len() != value_arr.len() {
            return Err(DataFusionError::Internal(
                "PivotFirst pivot and value arrays have different lengths".into(),
            ));
        }
        for row in 0..pivot_arr.len() {
            // Spark ignores the row entirely if either the pivot value is unmatched (index<0)
            // or the value is null. Matching Spark exactly here is important because
            // `PivotFirst.update` never writes for a null value, so a mid-batch null does not
            // clobber an earlier non-null.
            let pivot_scalar = ScalarValue::try_from_array(pivot_arr, row)?;
            if let Some(&slot_idx) = self.pivot_index.get(&pivot_scalar) {
                if !value_arr.is_null(row) {
                    self.slots[slot_idx] = Some(ScalarValue::try_from_array(value_arr, row)?);
                }
            }
        }
        Ok(())
    }

    fn evaluate(&mut self) -> DFResult<ScalarValue> {
        // Collapse the slot vector into a single ScalarValue::List whose inner array is
        // `slots.len()` items long, with typed nulls for empty slots. This matches Spark's
        // `PivotFirst.dataType = ArrayType(value_type)`.
        let scalars = (0..self.slots.len())
            .map(|i| self.slot_or_null(i))
            .collect::<DFResult<Vec<_>>>()?;
        let flat = ScalarValue::iter_to_array(scalars)?;
        Ok(SingleRowListArrayBuilder::new(flat).build_list_scalar())
    }

    fn size(&self) -> usize {
        std::mem::size_of_val(self)
            + self.slots.capacity() * std::mem::size_of::<Option<ScalarValue>>()
    }

    fn state(&mut self) -> DFResult<Vec<ScalarValue>> {
        // One ScalarValue per pivot slot; matches state_fields.
        (0..self.slots.len())
            .map(|i| self.slot_or_null(i))
            .collect()
    }

    fn merge_batch(&mut self, states: &[ArrayRef]) -> DFResult<()> {
        if states.len() != self.slots.len() {
            return Err(DataFusionError::Internal(format!(
                "PivotFirst merge expects {} state columns; got {}",
                self.slots.len(),
                states.len()
            )));
        }
        // Each column is one slot; each row is one incoming partial state. Any non-null cell
        // overwrites our current slot with "last write wins" (matches Spark's `PivotFirst.merge`).
        let n_rows = states.first().map(|a| a.len()).unwrap_or(0);
        for (slot_idx, col) in states.iter().enumerate() {
            for row in 0..n_rows {
                if !col.is_null(row) {
                    self.slots[slot_idx] = Some(ScalarValue::try_from_array(col, row)?);
                }
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use arrow::array::{Int32Array, StringArray};

    fn scalar(v: i32) -> ScalarValue {
        ScalarValue::Int32(Some(v))
    }
    fn s(v: &str) -> ScalarValue {
        ScalarValue::Utf8(Some(v.to_string()))
    }

    fn make_acc() -> PivotFirstAccumulator {
        let pivot_values = vec![s("a"), s("b"), s("c")];
        let mut pivot_index = HashMap::new();
        for (i, v) in pivot_values.iter().enumerate() {
            pivot_index.insert(v.clone(), i);
        }
        PivotFirstAccumulator::new(DataType::Int32, pivot_values, pivot_index)
    }

    #[test]
    fn update_writes_by_pivot_index() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["a", "c", "a"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![1, 3, 10]));
        acc.update_batch(&[pivots, values]).unwrap();
        // Slot 'a' = 10 (last non-null write wins for the same pivot value), slot 'b' = null,
        // slot 'c' = 3.
        assert_eq!(acc.slots, vec![Some(scalar(10)), None, Some(scalar(3))]);
    }

    #[test]
    fn update_ignores_unmatched_pivot() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["a", "z", "b"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![1, 99, 2]));
        acc.update_batch(&[pivots, values]).unwrap();
        // 'z' is not in the pivot list - its row is ignored entirely.
        assert_eq!(acc.slots, vec![Some(scalar(1)), Some(scalar(2)), None]);
    }

    #[test]
    fn update_ignores_null_value() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["a", "a"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![Some(5), None]));
        acc.update_batch(&[pivots, values]).unwrap();
        // The second row's null must not clobber the first row's 5.
        assert_eq!(acc.slots, vec![Some(scalar(5)), None, None]);
    }

    #[test]
    fn evaluate_returns_list_with_nulls_for_empty_slots() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["c"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![7]));
        acc.update_batch(&[pivots, values]).unwrap();

        let result = acc.evaluate().unwrap();
        match result {
            ScalarValue::List(list) => {
                assert_eq!(list.len(), 1);
                let inner = list.value(0);
                let inner = inner.as_any().downcast_ref::<Int32Array>().unwrap();
                assert!(inner.is_null(0));
                assert!(inner.is_null(1));
                assert_eq!(inner.value(2), 7);
            }
            other => panic!("expected ScalarValue::List, got {other:?}"),
        }
    }

    #[test]
    fn state_returns_one_scalar_per_slot() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["a", "c"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![1, 3]));
        acc.update_batch(&[pivots, values]).unwrap();

        let state = acc.state().unwrap();
        assert_eq!(state.len(), 3);
        assert_eq!(state[0], scalar(1));
        assert!(matches!(state[1], ScalarValue::Int32(None)));
        assert_eq!(state[2], scalar(3));
    }

    #[test]
    fn merge_pastes_non_null_slots() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["a"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![1]));
        acc.update_batch(&[pivots, values]).unwrap();

        // Build the other side's state and merge - slot 'a' stays 1, 'b' becomes 2, 'c' 3.
        let mut other = make_acc();
        let pivots2: ArrayRef = Arc::new(StringArray::from(vec!["b", "c"]));
        let values2: ArrayRef = Arc::new(Int32Array::from(vec![2, 3]));
        other.update_batch(&[pivots2, values2]).unwrap();
        let state = other.state().unwrap();
        // Feed each state scalar as a single-row column, mirroring what the shuffle produces.
        let state_arrays: Vec<ArrayRef> = state
            .into_iter()
            .map(|sv| sv.to_array_of_size(1).unwrap())
            .collect();
        acc.merge_batch(&state_arrays).unwrap();

        assert_eq!(
            acc.slots,
            vec![Some(scalar(1)), Some(scalar(2)), Some(scalar(3))]
        );
    }
}
