// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! Spark's `PivotFirst` aggregate. Used only by the second phase of the optimized pivot plan
//! generated by `PivotTransformer`. For each group, `PivotFirst` maintains an array of
//! `pivot_values.len()` slots; on each input row it evaluates the pivot column, looks up its
//! index in `pivot_values`, and writes the value column into that slot when a match is found
//! and the value is non-null. Rows with unmatched pivot values are ignored; matched rows with
//! a null value column leave the slot unchanged (matches Spark).
//!
//! State layout is one column per pivot slot, matching Spark's `aggBufferAttributes` (which
//! declares `indexSize` `AttributeReference`s, one per pivot value). This keeps the shuffle
//! schema between Partial and Final consistent with what Spark catalyst declared; otherwise
//! the shuffle exchange rejects the batch. `evaluate()` reassembles the slots into a
//! `ListArray` matching `PivotFirst.dataType = ArrayType(value_type)`.

use arrow::array::{Array, ArrayRef};
use arrow::datatypes::{DataType, Field, FieldRef};
use datafusion::common::utils::SingleRowListArrayBuilder;
use datafusion::common::{DataFusionError, Result as DFResult, ScalarValue};
use datafusion::logical_expr::function::{AccumulatorArgs, StateFieldsArgs};
use datafusion::logical_expr::Volatility::Immutable;
use datafusion::logical_expr::{Accumulator, AggregateUDFImpl, Signature};
use datafusion::physical_expr::expressions::format_state_name;
use std::collections::HashMap;
use std::sync::Arc;

/// UDAF implementation of Spark's `PivotFirst`.
///
/// `pivot_values` is a fixed, plan-time list of the pivot column values that occupy each
/// output slot; `pivot_index[v] = i` means an input row whose pivot column equals `v` writes
/// into slot `i`. Both the vector and the map are wrapped in `Arc` because `accumulator()`
/// fires once per group in a grouped aggregate and we want that path to bump a refcount
/// rather than deep-clone.
#[derive(Debug)]
pub struct SparkPivotFirst {
    signature: Signature,
    value_type: DataType,
    // Kept for `PartialEq`/`Hash` (identity of the aggregate for plan comparison) and for the
    // deterministic slot ordering `state_fields` needs. `HashMap` alone would give us the map
    // but not a stable order or a `Hash` impl.
    pivot_values: Arc<Vec<ScalarValue>>,
    pivot_index: Arc<HashMap<ScalarValue, usize>>,
}

impl PartialEq for SparkPivotFirst {
    fn eq(&self, other: &Self) -> bool {
        self.value_type == other.value_type && self.pivot_values == other.pivot_values
    }
}

impl Eq for SparkPivotFirst {}

impl std::hash::Hash for SparkPivotFirst {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.value_type.hash(state);
        self.pivot_values.hash(state);
    }
}

impl SparkPivotFirst {
    pub fn new(value_type: DataType, pivot_values: Vec<ScalarValue>) -> Self {
        let mut pivot_index = HashMap::with_capacity(pivot_values.len());
        // Spark's PivotFirst uses the FIRST occurrence's index (HashMap/TreeMap semantics), so
        // when duplicates are somehow present we mirror that by only inserting the first one.
        // `pivot_key` can fold two distinct pivot values (`0.0` and `-0.0`) onto one key, and can
        // drop one entirely (NaN), so the index is not necessarily the same length as the slot
        // vector - the slot count is always `pivot_values.len()`.
        for (i, v) in pivot_values.iter().enumerate() {
            if let Some(key) = pivot_key(v.clone()) {
                pivot_index.entry(key).or_insert(i);
            }
        }
        Self {
            signature: Signature::user_defined(Immutable),
            value_type,
            pivot_values: Arc::new(pivot_values),
            pivot_index: Arc::new(pivot_index),
        }
    }
}

/// Rewrite a pivot column value into the key Spark would match it on, or `None` when Spark can
/// never match it.
///
/// Spark's `PivotFirst` looks pivot values up in a Scala `HashMap[Any, Int]`, so matching goes
/// through `BoxesRunTime.equals` / `Statics.anyHash` on the boxed Catalyst value rather than
/// through `ScalarValue`'s own equality. The two disagree on floats in opposite directions:
///
/// * `-0.0` and `0.0` are one key for Spark (`-0.0 == 0.0` numerically, and `doubleHash` folds
///   both onto the hash of `0L`), while `ScalarValue` keeps them apart.
/// * `NaN` matches nothing for Spark, not even another `NaN`, because Scala's `==` on `Double`
///   is IEEE. `ScalarValue` treats `NaN` as equal to itself.
///
/// Nulls are left alone: a null pivot column value does match a null entry in the pivot list,
/// which is what Spark's `pivotIndex.getOrElse(null, -1)` does.
fn pivot_key(v: ScalarValue) -> Option<ScalarValue> {
    match v {
        ScalarValue::Float32(Some(f)) => {
            if f.is_nan() {
                None
            } else if f == 0.0 {
                Some(ScalarValue::Float32(Some(0.0)))
            } else {
                Some(ScalarValue::Float32(Some(f)))
            }
        }
        ScalarValue::Float64(Some(f)) => {
            if f.is_nan() {
                None
            } else if f == 0.0 {
                Some(ScalarValue::Float64(Some(0.0)))
            } else {
                Some(ScalarValue::Float64(Some(f)))
            }
        }
        other => Some(other),
    }
}

impl AggregateUDFImpl for SparkPivotFirst {
    fn name(&self) -> &str {
        "pivot_first"
    }

    fn signature(&self) -> &Signature {
        &self.signature
    }

    fn return_type(&self, _arg_types: &[DataType]) -> DFResult<DataType> {
        Ok(DataType::List(Arc::new(Field::new_list_field(
            self.value_type.clone(),
            true,
        ))))
    }

    fn state_fields(&self, args: StateFieldsArgs) -> DFResult<Vec<FieldRef>> {
        // One field per pivot slot, matching Spark's aggBufferAttributes so the shuffle
        // exchange sees the same schema catalyst declared. `format_state_name` is the same
        // helper other aggregates in this crate use (see `avg.rs`, `stddev.rs`).
        Ok((0..self.pivot_values.len())
            .map(|i| {
                Arc::new(Field::new(
                    format_state_name(args.name, &i.to_string()),
                    self.value_type.clone(),
                    true,
                ))
            })
            .collect())
    }

    fn accumulator(&self, _acc_args: AccumulatorArgs) -> DFResult<Box<dyn Accumulator>> {
        Ok(Box::new(PivotFirstAccumulator::new(
            self.value_type.clone(),
            Arc::clone(&self.pivot_index),
            self.pivot_values.len(),
        )))
    }
}

/// Per-group state: `slots[i]` holds the latest non-null value assigned to pivot slot `i`, or
/// `None` when nothing has written to that slot yet.
#[derive(Debug)]
struct PivotFirstAccumulator {
    value_type: DataType,
    pivot_index: Arc<HashMap<ScalarValue, usize>>,
    slots: Vec<Option<ScalarValue>>,
}

impl PivotFirstAccumulator {
    /// `num_slots` is the pivot list's length, which is what `state_fields` declares. It can
    /// exceed `pivot_index.len()` when pivot values collide under `pivot_key` or are unmatchable
    /// (NaN); those slots exist in the output and stay null.
    fn new(
        value_type: DataType,
        pivot_index: Arc<HashMap<ScalarValue, usize>>,
        num_slots: usize,
    ) -> Self {
        let slots = vec![None; num_slots];
        Self {
            value_type,
            pivot_index,
            slots,
        }
    }

    /// Turn slot `i` into a `ScalarValue`, substituting a typed null when the slot is empty.
    fn slot_or_null(&self, i: usize) -> DFResult<ScalarValue> {
        Ok(match &self.slots[i] {
            Some(v) => v.clone(),
            None => ScalarValue::try_from(&self.value_type)?,
        })
    }
}

impl Accumulator for PivotFirstAccumulator {
    fn update_batch(&mut self, values: &[ArrayRef]) -> DFResult<()> {
        if values.len() != 2 {
            return Err(DataFusionError::Internal(format!(
                "PivotFirst expects 2 inputs (pivot, value); got {}",
                values.len()
            )));
        }
        let pivot_arr = &values[0];
        let value_arr = &values[1];
        if pivot_arr.len() != value_arr.len() {
            return Err(DataFusionError::Internal(
                "PivotFirst pivot and value arrays have different lengths".into(),
            ));
        }
        for row in 0..pivot_arr.len() {
            // Spark ignores the row entirely if either the pivot value is unmatched (index<0)
            // or the value is null. Matching Spark exactly here is important because
            // `PivotFirst.update` never writes for a null value, so a mid-batch null does not
            // clobber an earlier non-null.
            let pivot_scalar = ScalarValue::try_from_array(pivot_arr, row)?;
            let Some(key) = pivot_key(pivot_scalar) else {
                // A NaN pivot value matches no slot in Spark, so the row is ignored.
                continue;
            };
            if let Some(&slot_idx) = self.pivot_index.get(&key) {
                if !value_arr.is_null(row) {
                    self.slots[slot_idx] = Some(ScalarValue::try_from_array(value_arr, row)?);
                }
            }
        }
        Ok(())
    }

    fn evaluate(&mut self) -> DFResult<ScalarValue> {
        // Collapse the per-slot state into a single ScalarValue::List with typed nulls for
        // empty slots. This matches Spark's `PivotFirst.dataType = ArrayType(value_type)`.
        let flat = ScalarValue::iter_to_array(self.state()?)?;
        Ok(SingleRowListArrayBuilder::new(flat).build_list_scalar())
    }

    fn size(&self) -> usize {
        std::mem::size_of_val(self)
            + self.slots.capacity() * std::mem::size_of::<Option<ScalarValue>>()
    }

    fn state(&mut self) -> DFResult<Vec<ScalarValue>> {
        // One ScalarValue per pivot slot; matches `state_fields`.
        (0..self.slots.len())
            .map(|i| self.slot_or_null(i))
            .collect()
    }

    fn merge_batch(&mut self, states: &[ArrayRef]) -> DFResult<()> {
        if states.len() != self.slots.len() {
            return Err(DataFusionError::Internal(format!(
                "PivotFirst merge expects {} state columns; got {}",
                self.slots.len(),
                states.len()
            )));
        }
        if states.is_empty() {
            return Ok(());
        }
        // Each column is one slot; each row is one incoming partial state. Any non-null cell
        // overwrites our current slot with "last write wins" (matches Spark's
        // `PivotFirst.merge`). Walk backwards and break on the first non-null so we only build
        // at most one `ScalarValue` per slot per merge, not one per row per slot.
        let n_rows = states[0].len();
        for (slot_idx, col) in states.iter().enumerate() {
            for row in (0..n_rows).rev() {
                if !col.is_null(row) {
                    self.slots[slot_idx] = Some(ScalarValue::try_from_array(col, row)?);
                    break;
                }
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use arrow::array::{Float32Array, Float64Array, Int32Array, StringArray};

    fn scalar(v: i32) -> ScalarValue {
        ScalarValue::Int32(Some(v))
    }
    fn s(v: &str) -> ScalarValue {
        ScalarValue::Utf8(Some(v.to_string()))
    }

    fn make_acc() -> PivotFirstAccumulator {
        let pivot_values = [s("a"), s("b"), s("c")];
        let pivot_index: HashMap<ScalarValue, usize> = pivot_values
            .iter()
            .enumerate()
            .map(|(i, v)| (v.clone(), i))
            .collect();
        PivotFirstAccumulator::new(DataType::Int32, Arc::new(pivot_index), pivot_values.len())
    }

    /// Build an accumulator the way the UDAF does, so the tests exercise `pivot_key` on both the
    /// index-building and the per-row lookup side.
    fn acc_for(value_type: DataType, pivot_values: Vec<ScalarValue>) -> PivotFirstAccumulator {
        let udaf = SparkPivotFirst::new(value_type.clone(), pivot_values.clone());
        PivotFirstAccumulator::new(
            value_type,
            Arc::clone(&udaf.pivot_index),
            pivot_values.len(),
        )
    }

    #[test]
    fn update_writes_by_pivot_index() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["a", "c", "a"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![1, 3, 10]));
        acc.update_batch(&[pivots, values]).unwrap();
        // Slot 'a' = 10 (last non-null write wins for the same pivot value), slot 'b' = null,
        // slot 'c' = 3.
        assert_eq!(acc.slots, vec![Some(scalar(10)), None, Some(scalar(3))]);
    }

    #[test]
    fn update_ignores_unmatched_pivot() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["a", "z", "b"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![1, 99, 2]));
        acc.update_batch(&[pivots, values]).unwrap();
        // 'z' is not in the pivot list - its row is ignored entirely.
        assert_eq!(acc.slots, vec![Some(scalar(1)), Some(scalar(2)), None]);
    }

    #[test]
    fn update_ignores_null_value() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["a", "a"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![Some(5), None]));
        acc.update_batch(&[pivots, values]).unwrap();
        // The second row's null must not clobber the first row's 5.
        assert_eq!(acc.slots, vec![Some(scalar(5)), None, None]);
    }

    #[test]
    fn evaluate_returns_list_with_nulls_for_empty_slots() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["c"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![7]));
        acc.update_batch(&[pivots, values]).unwrap();

        let result = acc.evaluate().unwrap();
        match result {
            ScalarValue::List(list) => {
                assert_eq!(list.len(), 1);
                let inner = list.value(0);
                let inner = inner.as_any().downcast_ref::<Int32Array>().unwrap();
                assert!(inner.is_null(0));
                assert!(inner.is_null(1));
                assert_eq!(inner.value(2), 7);
            }
            other => panic!("expected ScalarValue::List, got {other:?}"),
        }
    }

    #[test]
    fn state_returns_one_scalar_per_slot() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["a", "c"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![1, 3]));
        acc.update_batch(&[pivots, values]).unwrap();

        let state = acc.state().unwrap();
        assert_eq!(state.len(), 3);
        assert_eq!(state[0], scalar(1));
        assert!(matches!(state[1], ScalarValue::Int32(None)));
        assert_eq!(state[2], scalar(3));
    }

    #[test]
    fn merge_pastes_non_null_slots() {
        let mut acc = make_acc();
        let pivots: ArrayRef = Arc::new(StringArray::from(vec!["a"]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![1]));
        acc.update_batch(&[pivots, values]).unwrap();

        // Build the other side's state and merge - slot 'a' stays 1, 'b' becomes 2, 'c' 3.
        let mut other = make_acc();
        let pivots2: ArrayRef = Arc::new(StringArray::from(vec!["b", "c"]));
        let values2: ArrayRef = Arc::new(Int32Array::from(vec![2, 3]));
        other.update_batch(&[pivots2, values2]).unwrap();
        let state = other.state().unwrap();
        // Feed each state scalar as a single-row column, mirroring what the shuffle produces.
        let state_arrays: Vec<ArrayRef> = state
            .into_iter()
            .map(|sv| sv.to_array_of_size(1).unwrap())
            .collect();
        acc.merge_batch(&state_arrays).unwrap();

        assert_eq!(
            acc.slots,
            vec![Some(scalar(1)), Some(scalar(2)), Some(scalar(3))]
        );
    }

    #[test]
    fn signed_zero_pivot_values_are_one_key() {
        // Spark keys the pivot list on the boxed Catalyst value, where `-0.0 == 0.0`, so a
        // `-0.0` pivot column matches rows carrying either sign of zero. `ScalarValue` alone
        // keeps them distinct, which returned NULL for the whole column.
        //
        // Only positive zero appears on the input side on purpose: adding a `-0.0` row would
        // make the assertion hold either way, because the later write wins the slot regardless
        // of whether the `0.0` row matched.
        let mut acc = acc_for(
            DataType::Int32,
            vec![
                ScalarValue::Float64(Some(-0.0)),
                ScalarValue::Float64(Some(1.0)),
            ],
        );
        let pivots: ArrayRef = Arc::new(Float64Array::from(vec![0.0, 1.0]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![10, 30]));
        acc.update_batch(&[pivots, values]).unwrap();
        assert_eq!(acc.slots, vec![Some(scalar(10)), Some(scalar(30))]);
    }

    #[test]
    fn signed_zero_matches_in_both_directions() {
        // The mirror of the above: a `0.0` entry in the pivot list has to catch a `-0.0` row.
        let mut acc = acc_for(DataType::Int32, vec![ScalarValue::Float64(Some(0.0))]);
        let pivots: ArrayRef = Arc::new(Float64Array::from(vec![-0.0]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![42]));
        acc.update_batch(&[pivots, values]).unwrap();
        assert_eq!(acc.slots, vec![Some(scalar(42))]);
    }

    #[test]
    fn nan_pivot_value_matches_nothing() {
        // Scala's `==` on Double is IEEE, so `pivotIndex.getOrElse(NaN, -1)` never hits even
        // when NaN is in the pivot list. `ScalarValue` treats NaN as equal to itself, which
        // populated the column instead of leaving it NULL.
        let mut acc = acc_for(
            DataType::Int32,
            vec![
                ScalarValue::Float64(Some(f64::NAN)),
                ScalarValue::Float64(Some(2.0)),
            ],
        );
        let pivots: ArrayRef = Arc::new(Float64Array::from(vec![f64::NAN, 2.0]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![10, 20]));
        acc.update_batch(&[pivots, values]).unwrap();
        // The NaN slot still exists (the output column is declared) but stays null.
        assert_eq!(acc.slots, vec![None, Some(scalar(20))]);
    }

    #[test]
    fn unmatchable_pivot_value_keeps_its_state_slot() {
        // A NaN entry is dropped from the index, so the slot vector must be sized from the pivot
        // list rather than from the index, or `state()` would return fewer columns than
        // `state_fields` declares and the shuffle exchange would reject the batch.
        let mut acc = acc_for(
            DataType::Int32,
            vec![
                ScalarValue::Float64(Some(f64::NAN)),
                ScalarValue::Float64(Some(0.0)),
                ScalarValue::Float64(Some(-0.0)),
            ],
        );
        assert_eq!(acc.state().unwrap().len(), 3);
    }

    #[test]
    fn float32_signed_zero_and_nan_follow_the_same_rules() {
        let mut acc = acc_for(
            DataType::Int32,
            vec![
                ScalarValue::Float32(Some(-0.0)),
                ScalarValue::Float32(Some(f32::NAN)),
            ],
        );
        let pivots: ArrayRef = Arc::new(Float32Array::from(vec![0.0, f32::NAN]));
        let values: ArrayRef = Arc::new(Int32Array::from(vec![10, 20]));
        acc.update_batch(&[pivots, values]).unwrap();
        assert_eq!(acc.slots, vec![Some(scalar(10)), None]);
    }
}
