/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.comet.contrib.delta

import java.util.Locale

import scala.collection.mutable.ListBuffer
import scala.jdk.CollectionConverters._

import org.apache.spark.internal.Logging
import org.apache.spark.sql.catalyst.InternalRow
import org.apache.spark.sql.catalyst.expressions.{And, BoundReference, Expression, InterpretedPredicate}
import org.apache.spark.sql.catalyst.util.DateTimeUtils
import org.apache.spark.sql.comet.{CometDeltaNativeScanExec, CometDeltaScanMarker, CometNativeExec}
import org.apache.spark.sql.internal.SQLConf
import org.apache.spark.sql.types._
import org.apache.spark.unsafe.types.UTF8String

import org.apache.comet.{CometConf, ConfigEntry}
// Contrib-private Java proto types generated by protoc-jar-maven-plugin from
// contrib/delta/native/src/proto/delta_operator.proto. The proto declares
// `option java_package = "org.apache.comet.contrib.delta.proto"` so the generated
// outer class lands under a Comet-prefixed Java package.
// Typed Delta proto messages now live in core's operator.proto (alongside IcebergScan)
// instead of a contrib-private proto package.
import org.apache.comet.serde.OperatorOuterClass.{DeltaScan, DeltaScanCommon, DeltaScanTaskList}
import org.apache.comet.objectstore.NativeConfig
import org.apache.comet.serde.{CometOperatorSerde, Compatible, ExprOuterClass, OperatorOuterClass, SupportLevel}
import org.apache.comet.serde.ExprOuterClass.Expr
import org.apache.comet.serde.OperatorOuterClass.Operator
import org.apache.comet.serde.QueryPlanSerde.exprToProto
import org.apache.comet.serde.operator.schema2Proto

/**
 * Validation and serde logic for the native Delta Lake scan.
 *
 * `convert()` calls `Native.planDeltaScan` to enumerate files via `delta-kernel-rs`, builds the
 * `DeltaScanCommon` proto with schemas/filters/options, applies static partition pruning, and
 * stashes the task list in a ThreadLocal. `createExec()` retrieves it and builds a
 * `CometDeltaNativeScanExec` with split-mode serialization: common data serialized once at
 * planning time, per-partition task lists materialized lazily at execution time. DPP filters are
 * applied at execution time in the exec's `serializedPartitionData`.
 */
/**
 * Delta-scan serde + exec factory. Extends Comet's core `CometOperatorSerde` trait so
 * the existing convertToComet path in `CometExecRule` invokes it just like the
 * built-in handlers (CometNativeScan, CometIcebergNativeScan, ...). What is NOT here
 * is any *extension/discovery* SPI -- core's `CometExecRule` resolves this object via
 * `DeltaIntegration.scanHandler` (one reflective class lookup, no ServiceLoader, no
 * registry). The wire format is the typed `OpStruct::DeltaScan` variant.
 */
object CometDeltaNativeScan extends CometOperatorSerde[CometDeltaScanMarker] with Logging {

  /**
   * `kind` string for the `ContribOp` envelope this serde produces. The native side's
   * `comet-contrib-delta` rlib registers `DeltaScanPlanner` under this same kind via
   * `register_contrib_planner(DELTA_SCAN_KIND, ...)` in `contrib/delta/native/src/lib.rs`. Keep
   * the two in sync.
   */
  val DeltaScanKind: String = "delta-scan"

  /** Human-readable label for this scan implementation, used in diagnostic messages. */
  val ScanImpl: String = "native_delta_compat"

  /** Private lazy handle to the native library - one instance per JVM. */
  private lazy val nativeLib = new org.apache.comet.contrib.delta.Native()

  // Phase 5: stash the raw task-list bytes between convert() and createExec()
  // so the exec can do per-partition splitting at execution time. Single-threaded
  // during planning so a simple ThreadLocal is safe.
  private val lastTaskListBytes = new ThreadLocal[Array[Byte]]()

  // When a scan projects a per-file `_metadata.file_path` column, `DeltaScanRule` sets
  // `oneTaskPerPartition = true` in the marker's `DeltaScanMetadata`. We read it here to (a) skip
  // byte-range splitting in splitTasks and (b) emit `oneTaskPerPartition = true` on the
  // CometDeltaNativeScanExec so packTasks keeps each task in its own partition -- the native
  // plan emits one parquet file-group per file, so multiple files in one Spark partition would
  // drop the 2nd+ files' rows.
  /**
   * Translate Delta's `delta.columnMapping.id` metadata key to Spark+parquet's standard
   * `parquet.field.id` key on every StructField at every level of nesting. Required for
   * column-mapping `id` mode: Delta writes parquet files with `PARQUET:field_id` metadata
   * (i.e. the same field IDs it stores in its own metadata), but Spark's
   * `ParquetUtils.hasFieldId` -- and therefore Comet's serialisers -- only look at
   * `parquet.field.id`. Without this translation, `use_field_id=true` would still find
   * no IDs on the Spark schema and silently degrade to name-based matching.
   *
   * Top-level field metadata gets the new entry merged in via `MetadataBuilder`; nested
   * StructTypes recurse; ArrayType and MapType walk into their element/key/value types.
   * Fields without `delta.columnMapping.id` are passed through unchanged (e.g. partition
   * columns, synthetic row-index columns, struct-leaf fields the metadata strip elided).
   */
  /**
   * True for Delta's MATERIALISED row-tracking column names
   * (`_row-id-col-<uuid>` / `_row-commit-version-col-<uuid>`). These are real parquet
   * columns persisted when a file is rewritten to keep row IDs stable, read from the
   * file by name -- NOT synthesised. (Distinct from the logical `row_id` /
   * `row_commit_version` synthetic columns, which ARE synthesised from baseRowId +
   * row_index when no materialised column exists.)
   */
  private[delta] def isMaterializedRowTrackingName(name: String): Boolean = {
    val lc = name.toLowerCase(Locale.ROOT)
    lc.startsWith("_row-id-col-") || lc.startsWith("_row-commit-version-col-")
  }

  private[delta] def translateDeltaFieldIdToParquet(field: StructField): StructField = {
    val newDataType = translateDataTypeFieldIds(field.dataType)
    val newMetadata =
      if (field.metadata.contains(DeltaReflection.FieldIdMetadataKey) &&
        !field.metadata.contains(DeltaReflection.ParquetFieldIdMetadataKey)) {
        val fieldId = field.metadata.getLong(DeltaReflection.FieldIdMetadataKey)
        new org.apache.spark.sql.types.MetadataBuilder()
          .withMetadata(field.metadata)
          .putLong(DeltaReflection.ParquetFieldIdMetadataKey, fieldId)
          .build()
      } else field.metadata
    StructField(field.name, newDataType, field.nullable, newMetadata)
  }

  private def translateDataTypeFieldIds(
      dt: org.apache.spark.sql.types.DataType): org.apache.spark.sql.types.DataType =
    dt match {
      case s: StructType => StructType(s.fields.map(translateDeltaFieldIdToParquet))
      case a: org.apache.spark.sql.types.ArrayType =>
        org.apache.spark.sql.types.ArrayType(
          translateDataTypeFieldIds(a.elementType),
          a.containsNull)
      case m: org.apache.spark.sql.types.MapType =>
        org.apache.spark.sql.types.MapType(
          translateDataTypeFieldIds(m.keyType),
          translateDataTypeFieldIds(m.valueType),
          m.valueContainsNull)
      case other => other
    }

  private[delta] def scanNeedsOneTaskPerPartition(scan: CometDeltaScanMarker): Boolean =
    scan.deltaMetadata.oneTaskPerPartition

  /**
   * True when the native plan will emit one parquet file-group per file (core_glue's
   * `need_per_file_groups`): any `_metadata.*` virtual column / per-file row-tracking
   * constant (`base_row_id`, `default_row_commit_version`) is requested, or a synthesized
   * row-index / is-row-deleted / row_id / row_commit_version column is. These are all
   * per-file values, so each file becomes its own group. When a Spark partition packs
   * several files, those per-file groups execute concurrently and the synthetic-column
   * append can mis-align with / drop whole groups (non-deterministically) -- the same class
   * of bug fixed for materialised row-tracking columns and `input_file_name()`. Forcing one
   * file per partition keeps every native plan single-file-group. See
   * CometDeltaDefaultRowCommitVersionReproSuite / DefaultRowCommitVersionSuite,
   * [[isMaterializedRowTrackingName]], and `project_concurrent_missing_column_drop`.
   */
  private[delta] def needsPerFileGroups(scan: CometDeltaScanMarker): Boolean = {
    val outNames = scan.output.map(_.name.toLowerCase(Locale.ROOT)).toSet
    val reqNames = scan.requiredSchema.fieldNames.map(_.toLowerCase(Locale.ROOT)).toSet
    // `_metadata.*` virtual columns + per-file row-tracking constants (these always force
    // per-file groups natively because each carries a per-file value).
    val perFileMetadataNames = Set(
      "file_path",
      "file_name",
      "file_size",
      "file_block_start",
      "file_block_length",
      "file_modification_time",
      "base_row_id",
      "default_row_commit_version")
    // Synthesized columns (never physical): row index + is-row-deleted.
    val syntheticNames = Set(
      "__delta_internal_row_index",
      "_tmp_metadata_row_index",
      "__delta_internal_is_row_deleted")
    // row_id / row_commit_version are synthesized (-> per-file) only when row tracking is
    // enabled; otherwise they are ordinary user column names (see the emit-flag gating in
    // `convert`), so don't force per-file groups for them.
    val rowTrackingEnabled =
      DeltaReflection.extractMetadataConfiguration(scan.relation).exists { cfg =>
        cfg.get(DeltaReflection.EnableRowTrackingProp).exists(_.equalsIgnoreCase("true")) ||
          cfg.contains(DeltaReflection.MaterializedRowIdColumnProp) ||
          cfg.contains(DeltaReflection.MaterializedRowCommitVersionColumnProp)
      }
    outNames.exists(perFileMetadataNames.contains) ||
      reqNames.exists(syntheticNames.contains) ||
      (rowTrackingEnabled &&
        (reqNames.contains(DeltaReflection.RowIdColumnName) ||
          reqNames.contains(DeltaReflection.RowCommitVersionColumnName)))
  }

  /**
   * Reflectively resolve Hadoop's AWSCredentialProviderList for an s3/s3a URI and merge
   * the resulting (access, secret, optional token) triple into `baseOptions` under the
   * standard `fs.s3a.access.key` / `fs.s3a.secret.key` / `fs.s3a.session.token` keys --
   * the same keys `NativeConfig.extractObjectStoreOptions` would have picked up if the
   * user had set them explicitly in `core-site.xml`.
   *
   * Reflection is intentional: `hadoop-aws` is an optional dep; on a default Comet
   * deployment without S3 support on the classpath, `Class.forName` fails and we return
   * the base options unchanged. Non-s3/s3a URIs return base options unchanged too --
   * Azure / GCS / OSS resolve their own credential chains in kernel-rs's object_store
   * (or via the static keys already in `baseOptions`).
   *
   * Skip when the user has already set explicit static keys (don't overwrite an explicit
   * config with a resolved IAM-instance token).
   *
   * If reflection succeeds but credential resolution fails (e.g. IMDS unreachable, no
   * provider configured), log a warning and return `baseOptions` -- the engine will
   * still try anonymous access or surface a clearer error than a silent crash on first
   * S3 read.
   */
  // Cached reflective binding for the S3A credential chain. Resolved once per JVM.
  // The whole augment path is invoked on every Delta scan -- without caching, each scan
  // pays a Class.forName + getMethod round-trip just to find the bridge available.
  //
  // `None` means we tried once and failed (hadoop-aws not on classpath, signature drift,
  // etc.) -- subsequent calls short-circuit.
  private case class S3ACredentialBinding(
      createProviderList: java.lang.reflect.Method,
      getCredentials: java.lang.reflect.Method,
      getAccessKey: java.lang.reflect.Method,
      getSecretKey: java.lang.reflect.Method,
      sessionCredsCls: Option[Class[_]],
      getSessionToken: Option[java.lang.reflect.Method])

  @volatile private var s3aCredentialBindingCache: Option[Option[S3ACredentialBinding]] = None

  private def s3aCredentialBinding: Option[S3ACredentialBinding] =
    s3aCredentialBindingCache.getOrElse {
      val binding = try {
        // scalastyle:off classforname
        val utilsCls = Class.forName("org.apache.hadoop.fs.s3a.S3AUtils")
        // scalastyle:on classforname
        val createMethod = utilsCls.getMethod(
          "createAWSCredentialProviderList",
          classOf[java.net.URI],
          classOf[org.apache.hadoop.conf.Configuration])
        // Resolve the provider-list + credentials methods off the runtime classes
        // returned by createAWSCredentialProviderList. Method.invoke walks subclasses, so
        // a one-time lookup on the declared return / argument types is enough.
        val providerListCls = createMethod.getReturnType
        val getCredentialsMethod = providerListCls.getMethod("getCredentials")
        val credentialsCls = getCredentialsMethod.getReturnType
        val getAccessKeyMethod = credentialsCls.getMethod("getAWSAccessKeyId")
        val getSecretKeyMethod = credentialsCls.getMethod("getAWSSecretKey")
        val (sessionCredsCls, getSessionTokenMethod) = try {
          // scalastyle:off classforname
          val cls = Class.forName("com.amazonaws.auth.AWSSessionCredentials")
          // scalastyle:on classforname
          (Some(cls), Some(cls.getMethod("getSessionToken")))
        } catch { case _: ClassNotFoundException => (None, None) }
        Some(
          S3ACredentialBinding(
            createMethod,
            getCredentialsMethod,
            getAccessKeyMethod,
            getSecretKeyMethod,
            sessionCredsCls,
            getSessionTokenMethod))
      } catch {
        // hadoop-aws not on classpath, or signature drift -- mark as unavailable for the
        // rest of the JVM's lifetime.
        case _: ClassNotFoundException => None
        case _: NoSuchMethodException => None
        case scala.util.control.NonFatal(e) =>
          logWarning(
            s"S3A credential-chain reflection lookup failed; falling back to static-only " +
              s"keys in Delta log replay: ${e.getMessage}",
            e)
          None
      }
      s3aCredentialBindingCache = Some(binding)
      binding
    }

  private[delta] def augmentWithResolvedAwsCredentials(
      baseOptions: Map[String, String],
      tableRootUri: java.net.URI,
      hadoopConf: org.apache.hadoop.conf.Configuration): Map[String, String] = {
    val scheme = Option(tableRootUri.getScheme).map(_.toLowerCase).getOrElse("")
    if (scheme != "s3" && scheme != "s3a") return baseOptions
    if (baseOptions.contains("fs.s3a.access.key") &&
      baseOptions.contains("fs.s3a.secret.key")) {
      return baseOptions
    }
    s3aCredentialBinding match {
      case None => baseOptions // hadoop-aws not available; nothing to resolve
      case Some(binding) =>
        try {
          val providerList = binding.createProviderList.invoke(null, tableRootUri, hadoopConf)
          val credentials = binding.getCredentials.invoke(providerList)
          val accessKey = binding.getAccessKey.invoke(credentials)
          val secretKey = binding.getSecretKey.invoke(credentials)
          val sessionToken: Option[String] = (binding.sessionCredsCls, binding.getSessionToken) match {
            case (Some(cls), Some(m)) if cls.isInstance(credentials) =>
              Option(m.invoke(credentials)).map(_.toString)
            case _ => None
          }
          val resolved = scala.collection.mutable.Map[String, String]() ++= baseOptions
          Option(accessKey).map(_.toString).filter(_.nonEmpty).foreach { ak =>
            resolved("fs.s3a.access.key") = ak
          }
          Option(secretKey).map(_.toString).filter(_.nonEmpty).foreach { sk =>
            resolved("fs.s3a.secret.key") = sk
          }
          sessionToken.filter(_.nonEmpty).foreach { st =>
            resolved("fs.s3a.session.token") = st
          }
          resolved.toMap
        } catch {
          case scala.util.control.NonFatal(e) =>
            logWarning(
              s"Delta log-replay credential resolution failed for $tableRootUri: " +
                s"${e.getMessage}; falling back to static-only keys in storage options",
              e)
            baseOptions
        }
    }
  }

  override def enabledConfig: Option[ConfigEntry[Boolean]] = Some(
    DeltaConf.COMET_DELTA_NATIVE_ENABLED)

  override def getSupportLevel(operator: CometDeltaScanMarker): SupportLevel = Compatible()

  override def convert(
      scan: CometDeltaScanMarker,
      builder: Operator.Builder,
      childOp: OperatorOuterClass.Operator*): Option[OperatorOuterClass.Operator] = {

    // Resolve the table root via the HadoopFsRelation API - standard Spark, no spark-delta
    // compile-time dep required.
    val relation = scan.relation
    val tableRoot = DeltaReflection.extractTableRoot(relation).getOrElse {
      logWarning(
        s"CometDeltaNativeScan: unable to extract table root from relation " +
          s"${relation.location}; falling back to Spark's Delta reader.")
      return None
    }

    // Detect Delta synthetic columns the surrounding plan requested. We strip them
    // from the proto schemas sent to native so the parquet reader doesn't look for
    // columns that don't exist on disk, and set the proto emit flags so the dispatcher
    // wraps the parquet scan in `DeltaSyntheticColumnsExec` to append them back.
    //   - `__delta_internal_row_index` / `__delta_internal_is_row_deleted` are
    //     UPDATE/DELETE/MERGE internals (#144).
    //   - `row_id` / `row_commit_version` are row-tracking columns when the table has
    //     `delta.enableRowTracking=true` but no materialised columns -- synthesised
    //     from baseRowId + physical row index per task.
    // Row index can appear under either name in the scan output: the canonical
    // `__delta_internal_row_index` (Delta synthetic-column path), or the
    // intermediate `_tmp_metadata_row_index` (Delta's
    // `DeltaParquetFileFormat.TMP_METADATA_ROW_INDEX_COLUMN_NAME`, used for plans
    // that read `_metadata.row_index` from row-tracking-enabled tables before
    // Delta projects the alias). Both cases go through the same native synthesis
    // -- just with a different output column name.
    val rowIndexCanonicalPresent = scan.requiredSchema.fieldNames.exists(
      _.equalsIgnoreCase(DeltaReflection.RowIndexColumnName))
    val rowIndexTmpMetadataPresent = scan.requiredSchema.fieldNames.exists(
      _.equalsIgnoreCase(DeltaReflection.TmpMetadataRowIndexColumnName))
    // Both names denote the same physical value (the parquet row index), but they can
    // appear together in a single scan: DELETE/UPDATE/MERGE on a DV-enabled table with
    // `spark.databricks.delta.deletionVectors.useMetadataRowIndex=false` reads files that
    // already carry a deletion vector. There the scan needs `_metadata.row_index`
    // (-> `_tmp_metadata_row_index`) to APPLY the existing DV and the explicit
    // `__delta_internal_row_index` column to build the NEW DV bitmap. Native synthesis
    // emits a single row-index column under one name, and the final-reorder Projection
    // names its outputs from the wrapped (native) schema, so it cannot produce two
    // distinctly-named row-index outputs. Rather than misname them, fall back to Spark's
    // Delta reader for this scan. This shape only arises in Delta's internal DV-maintenance
    // read (never a user query), so there is no user-facing perf impact; the common
    // useMetadataRowIndex=true path (a single row-index name) is unaffected.
    // Repro: CometDeltaDeleteWithDVReproSuite; regression: DeleteSQLWithDeletionVectorsSuite.
    if (rowIndexCanonicalPresent && rowIndexTmpMetadataPresent) {
      logInfo(
        "CometDeltaNativeScan: scan.requiredSchema requests both " +
          s"${DeltaReflection.RowIndexColumnName} and " +
          s"${DeltaReflection.TmpMetadataRowIndexColumnName} (DV-maintenance read with " +
          "useMetadataRowIndex=false); falling back to Spark's Delta reader for this scan.")
      return None
    }
    val emitRowIndex = rowIndexCanonicalPresent || rowIndexTmpMetadataPresent
    val rowIndexColumnAlias: String =
      if (rowIndexTmpMetadataPresent && !rowIndexCanonicalPresent)
        DeltaReflection.TmpMetadataRowIndexColumnName
      else ""
    val emitIsRowDeleted = scan.requiredSchema.fieldNames.exists(
      _.equalsIgnoreCase(DeltaReflection.IsRowDeletedColumnName))
    // `row_id` / `row_commit_version` are reserved names ONLY when row tracking is enabled --
    // then they are metadata columns we synthesize (baseRowId + row_index, etc.). With row
    // tracking disabled they are ordinary user column names with no special meaning, and a
    // user table may legitimately have a physical column called `row_id`. Deriving the emit
    // flags purely from the column name mistook such a user column for the synthetic, stripped
    // it from the parquet read, and synthesized garbage (RowIdSuite "row_id column with row ids
    // disabled" -> NPE/wrong values). Gate the synthetic emit on row tracking actually being
    // enabled on the table. Repro: CometDeltaRowIdColumnCollisionReproSuite.
    val rowTrackingEnabled: Boolean =
      DeltaReflection.extractMetadataConfiguration(relation).exists { cfg =>
        cfg.get(DeltaReflection.EnableRowTrackingProp).exists(_.equalsIgnoreCase("true")) ||
          cfg.contains(DeltaReflection.MaterializedRowIdColumnProp) ||
          cfg.contains(DeltaReflection.MaterializedRowCommitVersionColumnProp)
      }
    val emitRowId = rowTrackingEnabled &&
      scan.requiredSchema.fieldNames.exists(_.equalsIgnoreCase(DeltaReflection.RowIdColumnName))
    val emitRowCommitVersion = rowTrackingEnabled &&
      scan.requiredSchema.fieldNames.exists(
        _.equalsIgnoreCase(DeltaReflection.RowCommitVersionColumnName))

    val ignoreMissingFiles =
      SQLConf.get.ignoreMissingFiles ||
        relation.options.get("ignoremissingfiles").contains("true")

    // Cloud storage options for kernel log replay and the native parquet reader,
    // keyed identically to NativeScan. See `resolveStorageOptions`.
    val storageOptions: java.util.Map[String, String] = resolveStorageOptions(scan, tableRoot)

    // Honor Delta's time-travel options (versionAsOf / timestampAsOf) via the Delta-
    // resolved snapshot version sitting on the FileIndex. Delta's analysis phase pins
    // the exact snapshot before we ever see the plan, so by the time the marker is
    // built, `relation.location` is a `PreparedDeltaFileIndex` whose toString looks like
    // `Delta[version=0, file:/...]`. We parse the version out via
    // `DeltaReflection.extractSnapshotVersion` and pass it through to kernel.
    //
    // When no version can be extracted (non-Delta file index, parser miss, etc.) we pass
    // -1 which asks kernel for the current latest snapshot.
    val snapshotVersion: Long =
      DeltaReflection.extractSnapshotVersion(relation).getOrElse(-1L)

    // Phase 2: serialize the data filters so kernel can apply stats-based file
    // pruning during log replay. The same filters will also be pushed down into
    // ParquetSource for row-group-level pruning - the two layers are additive.
    val predicateBytes: Array[Byte] = serializeSupportedDataFilters(scan)

    // Column name list for resolving BoundReference indices to kernel column
    // names. Must match the order of scan.output because exprToProto binds
    // attribute references by position in that schema.
    val columnNames: Array[String] = scan.output.map(_.name).toArray

    // --- 1. Get the active file list. ---
    //
    // Two code paths:
    //   (a) Pre-materialized FileIndex (`TahoeBatchFileIndex`, `CdcAddFileIndex`):
    //       Delta's streaming micro-batch reads AND MERGE / UPDATE / DELETE
    //       post-join rewrites both carry an exact `addFiles: Seq[AddFile]` on
    //       the FileIndex. Kernel log replay against the snapshot would return a
    //       DIFFERENT file set (the whole snapshot, or a version's deltas), which
    //       is a correctness hazard -- empty streaming batches, MERGE rewrites
    //       that see the whole table instead of only touched files. Build the
    //       DeltaScanTaskList proto directly from those AddFiles, skipping kernel.
    //   (b) Regular scan against a snapshot: call kernel for log replay as before.
    val taskListBytes =
      if (DeltaReflection.isBatchFileIndex(relation.location)) {
        // Pass BOTH the scan's partition filters AND data filters through
        // so `refreshedSnapshotFiles` (which queries
        // `snapshot.filesForScan(filters, ...)`) re-applies the same
        // partition pruning + stats-based data-skipping Delta did at
        // planning time. Without this, on `PreparedDeltaFileIndex` the
        // refresh path returns ALL files, breaking stats-based file
        // pruning (e.g. StatsCollectionSuite "gather stats" -- the
        // partition column is `odd` but the test filter is on `id` which
        // is a data column; only data-filter skipping makes the assertion
        // `recordsScanned(df.where("id = 1")) == 1` hold).
        DeltaReflection.extractBatchAddFiles(
          relation.location,
          scan.partitionFilters ++ scan.dataFilters) match {
          case Some(addFiles) =>
            // Under column mapping, Delta stores partition values in AddFile keyed by the
            // PHYSICAL column name. `relation.partitionSchema.fields[*].metadata` has had
            // Delta's columnMapping metadata stripped by HadoopFsRelation, so look in the
            // authoritative Snapshot schema (via reflection) and restrict to fields that
            // appear in the relation's partition schema.
            val partitionNames = relation.partitionSchema.fields.map(_.name).toSet
            val snapshotFields = DeltaReflection
              .extractSnapshotSchema(relation)
              .map(_.fields)
              .getOrElse(Array.empty[StructField])
            val physToLogical = snapshotFields.flatMap { f =>
              if (partitionNames.contains(f.name) &&
                f.metadata.contains(DeltaReflection.PhysicalNameMetadataKey)) {
                Some(f.metadata.getString(DeltaReflection.PhysicalNameMetadataKey) -> f.name)
              } else {
                None
              }
            }.toMap
            // DV handling: the driver only ships a DV DESCRIPTOR per AddFile
            // (storage type / path / offset / size, KB-scale). The executor decodes
            // via `dv_reader::read_dv_indexes` on first poll. Pre-#218 we called
            // `materializeDeletedRowIndexes` here and shipped the expanded
            // `Vec<u64>` -- a single 99M-row DV is a ~1 GB `long[]` retained on the
            // driver heap until the scan finishes. Matches the Iceberg contrib's
            // `IcebergScanCommon.delete_files_pool` pattern (driver = references,
            // executor = decode). If a DV file is missing/corrupt the executor
            // surfaces a `SparkException` -- same observable behaviour as before,
            // just at execution rather than planning.
            buildTaskListFromAddFiles(
              tableRoot,
              snapshotVersion,
              addFiles,
              nativeOp = null,
              columnNames,
              physicalToLogicalPartitionNames = physToLogical).toByteArray
          case None =>
            // Reflection failed; fall back conservatively.
            import org.apache.comet.CometSparkSessionExtensions.withFallbackReason
            withFallbackReason(
              scan,
              s"Native Delta scan could not extract AddFiles from " +
                s"${relation.location.getClass.getName}; falling back.")
            return None
        }
      } else {
        // Non-batch indexes (TahoeLogFileIndex, ...). DV-bearing
        // PreparedDeltaFileIndex is now classified as a batch index above
        // (see `isBatchFileIndex`), so its DV-fallback case is already
        // handled by the `case Some(_)` arm at the top of this match. For
        // remaining non-batch indexes the Delta-PreprocessTableWithDVs
        // wrapper detection upstream in `CometScanRule.scanBelowFallsBackForDvs`
        // is responsible for keeping DV-aware internal reads on vanilla.
        try {
          nativeLib.planDeltaScan(
            tableRoot,
            snapshotVersion,
            storageOptions,
            predicateBytes,
            columnNames)
        } catch {
          case scala.util.control.NonFatal(e) =>
            logWarning(
              s"CometDeltaNativeScan: delta-kernel-rs log replay failed for $tableRoot",
              e)
            return None
        }
      }
    val taskList0 = DeltaScanTaskList.parseFrom(taskListBytes)
    // The kernel path populates `column_mappings` from kernel's schema metadata.
    // The pre-materialised-index path (`buildTaskListFromAddFiles`) doesn't have
    // that information yet, so re-derive the mapping from the relation's data
    // + partition schema -- each StructField carries
    // `delta.columnMapping.physicalName` in its metadata when the table uses
    // column mapping. Without this the native scan can't translate logical
    // column references to physical parquet column names and returns nulls.
    // Fetch the schema used to resolve column-mapping physical names / field-ids. Prefer the
    // ANALYSIS-TIME schema that DeltaScanRule stashed from the original
    // DeltaParquetFileFormat.referenceSchema (relation.options): the FileIndex / live snapshot
    // may have moved on (RENAME COLUMN, overwriteSchema) since the query was analyzed, and the
    // query must read against the schema it was planned with -- otherwise a column whose
    // physical name / field-id changed reads the new data instead of NULL (DeltaColumnMapping
    // Suite "physical name changes" / "explicit id matching"). Fall back to the live snapshot
    // schema when the option is absent (e.g. the Delta-FileIndex-over-plain-ParquetFileFormat
    // shape, where referenceSchema was never available).
    val snapshotSchemaEarly: Option[StructType] =
      scan.deltaMetadata.analyzedSchema.orElse(DeltaReflection.extractSnapshotSchema(relation))
    // Only honour physicalName metadata when the table actually has column mapping
    // mode enabled. Some Delta test helpers (e.g. `DeltaSourceSuiteBase.withMetadata`)
    // call `DeltaColumnMapping.assignColumnIdAndPhysicalName` unconditionally, which
    // attaches `delta.columnMapping.physicalName` to every StructField even when the
    // table's `delta.columnMapping.mode` is unset / `none`. In that case the writer
    // still uses LOGICAL names in the parquet file, so physicalising our scan would
    // look up non-existent physical column names and return empty rows.
    val tableColumnMappingMode = DeltaReflection
      .extractMetadataConfiguration(relation)
      .flatMap(_.get("delta.columnMapping.mode"))
      .filter(m => m != null && !m.equalsIgnoreCase("none"))
    val taskList =
      if (!taskList0.getColumnMappingsList.isEmpty || tableColumnMappingMode.isEmpty) {
        taskList0
      } else {
        // `relation.dataSchema.fields[*].metadata` is stripped of Delta's column-mapping
        // metadata by HadoopFsRelation, so the lookup here nearly always returns empty.
        // Use the Snapshot schema we extracted (which preserves physical names at every
        // level) for the data-column mappings, and `relation.partitionSchema` only for
        // partition columns (whose metadata isn't stripped).
        val dataFieldsSource: Array[StructField] =
          snapshotSchemaEarly.map(_.fields).getOrElse(relation.dataSchema.fields)
        val allFields = dataFieldsSource ++ relation.partitionSchema.fields
        val logicalToPhysical = allFields.flatMap { f =>
          if (f.metadata.contains(DeltaReflection.PhysicalNameMetadataKey)) {
            Some(f.name -> f.metadata.getString(DeltaReflection.PhysicalNameMetadataKey))
          } else {
            None
          }
        }
        if (logicalToPhysical.isEmpty) {
          taskList0
        } else {
          val b = DeltaScanTaskList.newBuilder(taskList0)
          logicalToPhysical.foreach { case (logical, physical) =>
            b.addColumnMappings(
              OperatorOuterClass.DeltaColumnMapping
                .newBuilder()
                .setLogicalName(logical)
                .setPhysicalName(physical)
                .build())
          }
          b.build()
        }
      }

    // Phase 6 reader-feature gate. Kernel reports any Delta reader features that
    // are currently in use in this snapshot and that Comet's native path does NOT
    // correctly handle. Falling back is mandatory for correctness: reading through
    // the native path would silently produce wrong results (e.g. returning rows
    // that a deletion vector should have hidden). The gate becomes obsolete feature
    // by feature as later phases ship:
    //   deletionVectors -> Phase 3
    //   columnMapping   -> Phase 4
    //   typeWidening    -> future phase
    //   rowTracking     -> future phase
    val unsupportedFeatures = taskList.getUnsupportedFeaturesList.asScala.toSeq
    if (unsupportedFeatures.nonEmpty &&
      DeltaConf.COMET_DELTA_FALLBACK_ON_UNSUPPORTED_FEATURE.get(scan.conf)) {
      logInfo(
        s"CometDeltaNativeScan: falling back for table $tableRoot " +
          s"due to unsupported reader features: ${unsupportedFeatures.mkString(", ")}")
      import org.apache.comet.CometSparkSessionExtensions.withFallbackReason
      withFallbackReason(
        scan,
        s"Native Delta scan does not yet support these features in use on this " +
          s"snapshot: ${unsupportedFeatures.mkString(", ")}. Falling back to Spark's " +
          s"Delta reader. Set ${DeltaConf.COMET_DELTA_FALLBACK_ON_UNSUPPORTED_FEATURE.key}=false " +
          s"to bypass this check (NOT recommended - may produce incorrect results).")
      return None
    }

    // Apply Spark's partition filters to the task list so that queries like
    // `WHERE partition_col = X` don't drag in files from other partitions. Kernel
    // itself is given the whole snapshot (no predicate yet - that lands in Phase 2),
    // so we do the pruning in Scala by evaluating each task's partition-value map
    // against Spark's `partitionFilters`. This is a single driver-side loop; filtered
    // tasks never go over the wire to executors.
    val filteredTasks0 =
      prunePartitions(taskList.getTasksList.asScala.toSeq, scan, relation.partitionSchema)

    // Split files larger than `maxSplitBytes` into byte-range chunks so a single
    // big parquet file can be read across multiple Spark partitions, matching
    // Spark's `FilePartition.splitFiles` semantics. This is what makes
    // FILES_MAX_PARTITION_BYTES, files.openCostInBytes, and
    // files.minPartitionNum take effect on Delta tables: without it every file
    // is exactly one partition and the *.size assertions in
    // DeletionVectorsSuite's PredicatePushdown tests fail (they configure
    // FILES_MAX_PARTITION_BYTES=2MB on a multi-row-group fixture and assert
    // exactly 2 splits).
    val filteredTasks =
      splitTasks(scan, filteredTasks0)

    // --- 2. Build the common block ---
    val commonBuilder = DeltaScanCommon.newBuilder()
    commonBuilder.setSource(scan.simpleStringWithNodeId())
    commonBuilder.setTableRoot(taskList.getTableRoot)
    commonBuilder.setSnapshotVersion(taskList.getSnapshotVersion)
    commonBuilder.setSessionTimezone(scan.conf.sessionLocalTimeZone)
    commonBuilder.setCaseSensitive(scan.conf.getConf[Boolean](SQLConf.CASE_SENSITIVE))
    commonBuilder.setIgnoreMissingFiles(ignoreMissingFiles)
    commonBuilder.setDataFileConcurrencyLimit(
      DeltaConf.COMET_DELTA_DATA_FILE_CONCURRENCY_LIMIT.get())

    // Schemas. Delta is different from vanilla Parquet: `relation.dataSchema` on a Delta
    // table INCLUDES partition columns, but the physical parquet files on disk do NOT.
    // So we compute the actual file schema by subtracting the partition columns from
    // `relation.dataSchema`. Mirrors what delta-kernel itself reports as the scan schema.
    val partitionNames =
      relation.partitionSchema.fields.map(_.name.toLowerCase(Locale.ROOT)).toSet
    // Materialised row-tracking columns (`_row-id-col-<uuid>` /
    // `_row-commit-version-col-<uuid>`) are REAL parquet columns written when a file is
    // rewritten (OPTIMIZE / z-order / compaction / MERGE) to persist stable row IDs.
    // They are NOT in `relation.dataSchema` (row tracking is metadata, not the logical
    // schema), but they ARE in `scan.requiredSchema`, matched in the file BY NAME. Add
    // them to the file data schema so the native parquet reader actually reads them
    // (returning null for files that don't carry them -- unmaterialised -- which is
    // exactly what Delta's downstream `coalesce(_metadata.row_id, base_row_id +
    // row_index)` needs). Treating them as synthetic (the previous behaviour) made the
    // scan synthesise base_row_id+row_index instead, so row IDs were not stable across
    // rewrites. See F3 in docs/08-known-limitations.md.
    // Delta also allows the materialised row-id / row-commit-version columns to have a
    // CUSTOM physical name, declared in the table config under
    // `delta.rowTracking.materialized{RowId,RowCommitVersion}ColumnName` (e.g. tables
    // CONVERTed from parquet, or set explicitly). Those names don't match the
    // `_row-id-col-*` prefix, so detect them from the table configuration too. Missing
    // this leaves such a column in `requiredSchema` but NOT in the file data schema, and
    // `final_output_indices` then points past the native schema -> native plan_delta_scan
    // index-out-of-bounds panic (RowIdSuite).
    val customMaterializedColNames: Set[String] =
      DeltaReflection
        .extractMetadataConfiguration(relation)
        .map { cfg =>
          Seq(
            DeltaReflection.MaterializedRowIdColumnProp,
            DeltaReflection.MaterializedRowCommitVersionColumnProp).flatMap(cfg.get).toSet
        }
        .getOrElse(Set.empty)
    val materializedRowTrackingFields: Array[StructField] =
      scan.requiredSchema.fields
        .filter(f =>
          CometDeltaNativeScan.isMaterializedRowTrackingName(f.name) ||
            customMaterializedColNames.contains(f.name))
        .map(f => StructField(f.name, f.dataType, f.nullable))
    val fileDataSchemaFields =
      relation.dataSchema.fields.filterNot(f =>
        partitionNames.contains(f.name.toLowerCase(Locale.ROOT))) ++
        materializedRowTrackingFields

    // When column mapping (id or name) is active, Delta writes parquet files using physical
    // names at EVERY level of nesting -- struct inner fields, array elements, map keys/values.
    // `schema2Proto` otherwise serialises the Spark StructField tree with logical names, so the
    // native parquet reader would look for e.g. `b1` and its inner `c` but the file has
    // `col-<uuid1>` and `col-<uuid2>`, yielding a null-struct read. Substitute physical names
    // recursively before serialising so the proto schema matches the on-disk names at every
    // level. The `column_mappings` proto carries only top-level logical->physical so that
    // filter column references (expressed with logical names) still translate correctly.
    // Detect column mapping from the most reliable sources:
    //  1. Kernel-side proto already populated the flat logical->physical map, OR
    //  2. `relation.dataSchema` StructField metadata carries the physical-name key (rare --
    //     HadoopFsRelation strips this on construction, but iceberg-compat paths don't), OR
    //  3. the Delta snapshot's Metadata.configuration declares `delta.columnMapping.mode`
    //     not equal to `none`. This is the authoritative source and catches the case where
    //     (1) and (2) both miss.
    // A false negative here is silent data-corruption (physicalisation skipped, native reader
    // looks for logical names in physical-named parquet), so the fallback probe is important.
    val columnMappingActive = taskList.getColumnMappingsList.asScala.nonEmpty ||
      relation.dataSchema.fields.exists(
        _.metadata.contains(DeltaReflection.PhysicalNameMetadataKey)) ||
      DeltaReflection
        .extractMetadataConfiguration(relation)
        .flatMap(_.get("delta.columnMapping.mode"))
        .exists(m => m != null && !m.equalsIgnoreCase("none"))
    // `relation.dataSchema` has its StructField metadata stripped by Spark's HadoopFsRelation
    // construction, so nested physical names are invisible. Reuse the snapshot schema fetched
    // above (or None when column mapping isn't active).
    val snapshotSchema: Option[StructType] =
      if (columnMappingActive) snapshotSchemaEarly else None
    val physicalByLogicalName: Map[String, StructField] =
      snapshotSchema.map(_.fields.map(f => f.name -> f).toMap).getOrElse(Map.empty)
    // Preserve the top-level LOGICAL name and substitute only NESTED (struct/map/array) inner
    // field names with their physical equivalents. The native planner (planner.rs ~1383)
    // already handles top-level logical->physical substitution using the flat `column_mappings`
    // proto. Fields not present in the snapshot (e.g. synthetic `_tmp_metadata_row_index`) are
    // passed through untouched.
    def physicaliseNestedTypesOnly(f: StructField): StructField =
      physicalByLogicalName.get(f.name) match {
        case Some(metaField) =>
          StructField(f.name, physicaliseDataType(metaField.dataType), f.nullable, f.metadata)
        case None => f
      }
    // For `required_schema` we MUST preserve the field's pruned shape (Spark's
    // nested column pruning can leave a struct with only the accessed children) while
    // still rewriting nested names to their physical equivalents. Using the data-schema
    // helper above (which replaces the whole struct with the snapshot's full shape)
    // would lose pruning and produce nested children Spark's plan does not expect,
    // causing GetStructField ordinals to point at the wrong child. Walks `req`'s tree
    // and pairs each node with the corresponding snapshot node by logical name to find
    // the physical name; fields not present in the snapshot pass through untouched.
    def physicaliseDataTypePreserving(req: DataType, snap: DataType): DataType =
      (req, snap) match {
        case (rs: StructType, ms: StructType) =>
          val snapByLogical = ms.fields.map(f => f.name -> f).toMap
          StructType(rs.fields.map { rf =>
            snapByLogical.get(rf.name) match {
              case Some(mf) =>
                val physName =
                  if (mf.metadata.contains(DeltaReflection.PhysicalNameMetadataKey)) {
                    mf.metadata.getString(DeltaReflection.PhysicalNameMetadataKey)
                  } else rf.name
                StructField(
                  physName,
                  physicaliseDataTypePreserving(rf.dataType, mf.dataType),
                  rf.nullable,
                  rf.metadata)
              case None => rf
            }
          })
        case (ra: ArrayType, ma: ArrayType) =>
          ArrayType(
            physicaliseDataTypePreserving(ra.elementType, ma.elementType),
            ra.containsNull)
        case (rm: MapType, mm: MapType) =>
          MapType(
            physicaliseDataTypePreserving(rm.keyType, mm.keyType),
            physicaliseDataTypePreserving(rm.valueType, mm.valueType),
            rm.valueContainsNull)
        case _ => req
      }
    def physicaliseRequiredField(f: StructField): StructField =
      physicalByLogicalName.get(f.name) match {
        case Some(metaField) =>
          StructField(
            f.name,
            physicaliseDataTypePreserving(f.dataType, metaField.dataType),
            f.nullable,
            f.metadata)
        case None => f
      }
    // `data_schema` describes what we want the native parquet reader to read from
    // the file. Under column mapping, parquet column matching is by PHYSICAL name
    // (at every level of nesting). The reader projects by leaf column path -- it
    // can read just `b.col-d` even if the file's `b` also has `col-c`. To make
    // that happen, we send data_schema with the SAME shape as the required output:
    // top-level fields that are required carry the pruned + physicalised nested
    // shape; non-required top-level fields keep their full physicalised shape (no
    // read attempt is made for them anyway because they don't appear in
    // projection_vector). Without this overlay, the reader would emit a struct
    // with ALL nested children (full file shape), and upstream GetStructField
    // ordinals -- computed by Catalyst against the PRUNED required_schema --
    // would pick the wrong child. Manifested as "Invalid comparison Utf8 <= Int32"
    // on `b.d > 0` (d is INT, ordinal 0 in pruned `b: struct<d>`, but ordinal 0
    // in the file struct is `c` STRING). #79 fix 2026-05-13.
    // `requiredSchema` on the wire is the SCAN's output schema -- i.e. data columns the
    // scan reads from parquet PLUS partition columns it materialises from
    // PartitionedFile.partition_values. Upstream operators in the native plan tree bind
    // their column references by index into this schema. For non-partitioned tables
    // `scan.requiredSchema` is the whole output already; for partitioned tables Spark
    // gives us just the data half here, so we append the partition fields at the tail to
    // match the layout indices in `projection_vector` resolve into.
    val partitionFieldsForRequired: Array[StructField] = {
      val haveLc = scan.requiredSchema.fields.map(_.name.toLowerCase(Locale.ROOT)).toSet
      relation.partitionSchema.fields.filterNot(f =>
        haveLc.contains(f.name.toLowerCase(Locale.ROOT)))
    }
    // Spark `_metadata.*` virtual columns plus Delta row-tracking synthetics that
    // appear in scan.output but not scan.requiredSchema. They are synthesised natively
    // below (via metadataColumnNamesEmitted) and must appear in the wrapped exec
    // output schema for downstream attribute resolution.
    val sparkMetadataNameSet = Set(
      "file_path",
      "file_name",
      "file_size",
      "file_block_start",
      "file_block_length",
      "file_modification_time")
    def isExtraSyntheticName(name: String): Boolean = {
      val lc = name.toLowerCase(Locale.ROOT)
      // NOTE: materialised row-tracking columns (`_row-id-col-*` /
      // `_row-commit-version-col-*`) are deliberately NOT here -- they are real
      // parquet columns read from the file (added to the data schema), not synthesised.
      sparkMetadataNameSet.contains(lc) ||
        lc == "base_row_id" ||
        lc == "default_row_commit_version"
    }
    val extraMetadataFields: Array[StructField] = scan.output.toArray.collect {
      case a if isExtraSyntheticName(a.name) &&
        !scan.requiredSchema.fieldNames.exists(_.equalsIgnoreCase(a.name)) =>
        StructField(a.name, a.dataType, a.nullable)
    }
    val requiredSchemaFields = {
      val base =
        if (columnMappingActive) scan.requiredSchema.fields.map(physicaliseRequiredField)
        else scan.requiredSchema.fields
      base ++ partitionFieldsForRequired ++ extraMetadataFields
    }
    val physicalFileDataSchemaFields = if (columnMappingActive) {
      val requiredByName = requiredSchemaFields
        .map(f => f.name.toLowerCase(Locale.ROOT) -> f)
        .toMap
      fileDataSchemaFields.map { f =>
        requiredByName.get(f.name.toLowerCase(Locale.ROOT)) match {
          // Required asks for this field -- adopt its pruned, physicalised shape so
          // the parquet reader projects only the required nested children.
          case Some(req) => StructField(f.name, req.dataType, f.nullable, f.metadata)
          // Field not required -- physicalise the full snapshot shape (used only if
          // some other consumer references it; harmless when projection_vector skips it).
          case None => physicaliseNestedTypesOnly(f)
        }
      }
    } else fileDataSchemaFields

    // Column-mapping `id` mode: Delta stores the parquet field ID on every
    // StructField (at every level of nesting) under
    // `delta.columnMapping.id`. Spark's `ParquetUtils.hasFieldId` (used by
    // `schema2Proto` and the StructType arm of `serializeDataType`) reads from
    // `parquet.field.id`. Walk the schema tree and translate keys so the
    // native side -- when `use_field_id=true` -- matches Spark schema fields
    // to parquet file fields by ID instead of by name.
    val cmModeIsId = DeltaReflection
      .extractMetadataConfiguration(relation)
      .flatMap(_.get("delta.columnMapping.mode"))
      .exists(_.equalsIgnoreCase("id"))
    // The general-purpose Parquet field-ID read path also drives `use_field_id`: if
    // the user has enabled `spark.sql.parquet.fieldId.read.enabled` AND the required
    // schema already carries Spark's `parquet.field.id` metadata, route through the
    // same native machinery. CM-id mode is the common Delta case; this catches
    // non-Delta-id tables that nevertheless want field-ID matching.
    val sparkFieldIdReadEnabled = SQLConf.get.getConf(SQLConf.PARQUET_FIELD_ID_READ_ENABLED) &&
      org.apache.spark.sql.execution.datasources.parquet.ParquetUtils.hasFieldIds(
        scan.requiredSchema)
    val useFieldIdActive = cmModeIsId || sparkFieldIdReadEnabled
    val dataSchemaForProto =
      if (cmModeIsId) {
        physicalFileDataSchemaFields.map(
          CometDeltaNativeScan.translateDeltaFieldIdToParquet)
      } else physicalFileDataSchemaFields
    val requiredSchemaForProto =
      if (cmModeIsId) {
        requiredSchemaFields.map(CometDeltaNativeScan.translateDeltaFieldIdToParquet)
      } else requiredSchemaFields
    val partitionSchemaForProto =
      if (cmModeIsId) {
        relation.partitionSchema.fields.map(
          CometDeltaNativeScan.translateDeltaFieldIdToParquet)
      } else relation.partitionSchema.fields

    // Strip Delta synthetic columns from the proto schemas. They're not on disk so the
    // native parquet reader must not look for them; `DeltaSyntheticColumnsExec` appends
    // them back after the scan. Required precondition: synthetics must be a SUFFIX of
    // scan.requiredSchema -- otherwise the appended order wouldn't match Spark's
    // expected output. The standard Delta DV-rewrite path satisfies this; anything else
    // falls back. If we detect the suffix doesn't hold, decline and let Spark's reader
    // handle it (correctness over coverage).
    val syntheticNames = Set(
      DeltaReflection.RowIndexColumnName.toLowerCase(Locale.ROOT),
      DeltaReflection.TmpMetadataRowIndexColumnName.toLowerCase(Locale.ROOT),
      DeltaReflection.IsRowDeletedColumnName.toLowerCase(Locale.ROOT),
      DeltaReflection.RowIdColumnName,
      DeltaReflection.RowCommitVersionColumnName,
      // Spark `_metadata.*` virtual columns synthesised natively per-task.
      "file_path",
      "file_name",
      "file_size",
      "file_block_start",
      "file_block_length",
      "file_modification_time",
      // Delta row-tracking columns synthesised natively. Both are per-file constants
      // from AddFile.baseRowId / AddFile.defaultRowCommitVersion; the materialised
      // columns are null when the parquet file doesn't carry them. Must be kept in
      // sync with `fixedMetadataNames` below and the proto setters in
      // `buildTaskListFromAddFiles` so the native side actually emits these.
      "base_row_id",
      "default_row_commit_version")
    val isSynthetic = (f: StructField) => {
      // Materialised row-tracking columns are NOT synthetic -- they are read from
      // parquet (see `materializedRowTrackingFields`), so they must stay in the
      // proto data/required schemas.
      syntheticNames.contains(f.name.toLowerCase(Locale.ROOT))
    }
    // metadataColumnNames includes the Spark `_metadata.*` virtual columns (file_path,
    // file_name, file_size, file_block_start, file_block_length, file_modification_time)
    // that Delta's strategies inject. These are synthesised per-task in
    // `DeltaSyntheticColumnsExec`, so when any are required we need the synthetic-emit
    // path even without emit_row_index/is_row_deleted/row_id/row_commit_version set.
    val sparkMetadataNames = Set(
      "file_path",
      "file_name",
      "file_size",
      "file_block_start",
      "file_block_length",
      "file_modification_time")
    val requiredFieldNamesLower: Set[String] =
      scan.requiredSchema.fields.map(_.name.toLowerCase(Locale.ROOT)).toSet
    // Spark also appends `_metadata.*` columns to scan.output (not requiredSchema) when
    // downstream operators (e.g. Delta's PreprocessTableWithDVs) bind to them by name.
    // The wrapped exec's output schema must include them so attribute resolution works.
    val outputFieldNamesLower: Set[String] =
      scan.output.map(_.name.toLowerCase(Locale.ROOT)).toSet
    val fixedMetadataNames = Set(
      "file_path",
      "file_name",
      "file_size",
      "file_block_start",
      "file_block_length",
      "file_modification_time",
      "base_row_id",
      // Delta row-tracking exposes `default_row_commit_version` as a per-file
      // metadata column alongside `base_row_id`. Missing this here means the
      // emit-name list passed to native drops the column, causing the
      // upstream operator to see N-1 cols where Spark expected N (e.g. CDC
      // reads on row-tracking-enabled tables, especially under
      // coordinated-commits backfill where this code path is reached).
      "default_row_commit_version")
    // The wrapped exec output is `parquet projection ++ row_index/is_row_deleted/...
    // ++ metadata_column_names` in the order metadata names are emitted. To make the
    // post-synthesis layout match scan.output WITHOUT a final reorder Project, walk
    // scan.output and pick out the metadata-style columns in the order they appear.
    val metadataColumnNamesEmitted: Seq[String] = scan.output.flatMap { attr =>
      val lc = attr.name.toLowerCase(Locale.ROOT)
      // Materialised row-tracking columns are read from parquet, not synthesised, so
      // they are excluded here.
      if (fixedMetadataNames.contains(lc)) Some(lc) else None
    }.distinct
    val needsMetadataEmit = metadataColumnNamesEmitted.nonEmpty
    val needsSyntheticEmit =
      emitRowIndex || emitIsRowDeleted || emitRowId || emitRowCommitVersion || needsMetadataEmit
    // When synthetics are NOT a contiguous suffix of required_schema, build a reorder
    // map: for each original required-schema position, an index into the wrapped exec's
    // output (parquet output cols followed by appended synthetics in canonical order
    // row_index, is_row_deleted, row_id, row_commit_version). The native dispatcher
    // applies a final ProjectionExec to reorder columns to match Spark's expected
    // output layout. Empty when synthetics ARE a suffix -- already in the right order.
    val finalOutputIndices: Seq[Int] = computeFinalOutputIndices(
      needsSyntheticEmit,
      requiredSchemaForProto,
      isSynthetic,
      emitRowIndex,
      emitIsRowDeleted,
      emitRowId,
      emitRowCommitVersion,
      rowIndexColumnAlias,
      metadataColumnNamesEmitted)
    val requiredSchemaForProtoStripped =
      if (needsSyntheticEmit) requiredSchemaForProto.filterNot(isSynthetic)
      else requiredSchemaForProto
    val dataSchemaForProtoStripped =
      if (needsSyntheticEmit) dataSchemaForProto.filterNot(isSynthetic)
      else dataSchemaForProto

    val dataSchema = schema2Proto(dataSchemaForProtoStripped)
    val requiredSchema = schema2Proto(requiredSchemaForProtoStripped)
    val partitionSchema = schema2Proto(partitionSchemaForProto)
    commonBuilder.addAllDataSchema(dataSchema.toIterable.asJava)
    commonBuilder.addAllRequiredSchema(requiredSchema.toIterable.asJava)
    commonBuilder.addAllPartitionSchema(partitionSchema.toIterable.asJava)
    commonBuilder.setUseFieldId(useFieldIdActive)
    commonBuilder.setEmitRowIndex(emitRowIndex)
    commonBuilder.setEmitIsRowDeleted(emitIsRowDeleted)
    commonBuilder.setEmitRowId(emitRowId)
    commonBuilder.setEmitRowCommitVersion(emitRowCommitVersion)
    if (rowIndexColumnAlias.nonEmpty) {
      commonBuilder.setRowIndexColumnAlias(rowIndexColumnAlias)
    }
    // Add the `_metadata.*` virtual column names we will synthesise natively (computed
    // above as `metadataColumnNamesEmitted` from `scan.requiredSchema`).
    metadataColumnNamesEmitted.foreach(commonBuilder.addMetadataColumnNames)
    commonBuilder.addAllFinalOutputIndices(
      finalOutputIndices.map(i => Integer.valueOf(i)).asJava)

    // Projection vector maps output positions to (file_data_schema ++ partition_schema)
    // indices. Spark's `FileSourceScanExec` splits its visible schema into
    // `requiredSchema` (data-only columns that must be read from parquet) and an
    // implicit partition tail that is materialised from `PartitionedFile.partition_values`.
    // The scan's `output` is `requiredSchema ++ partitionSchema` in that order.
    //
    // We mirror that layout: first emit one index per required (data) field pointing
    // into `fileDataSchemaFields`, then append one index per partition field pointing
    // at `fileDataSchemaFields.length + partitionIdx` so the native side resolves those
    // positions against `PartitionedFile.partition_values`.
    //
    // If `scan.requiredSchema` ever contains a partition column (some Delta code paths
    // leak one in), we resolve it through the partition tail without re-reading from
    // parquet.
    val partitionNameToIndex: Map[String, Int] =
      relation.partitionSchema.fields.zipWithIndex.map { case (f, i) =>
        f.name.toLowerCase(Locale.ROOT) -> i
      }.toMap
    // Skip synthetic columns from the projection: DeltaSyntheticColumnsExec
    // appends them after the parquet read. The data-schema seen by native is
    // `dataSchemaForProtoStripped` (== fileDataSchemaFields with synthetics
    // filtered out when needsSyntheticEmit). Indexes here must reflect that:
    // (a) within the data tail, fileDataSchemaFields.indexWhere walks the
    //     un-stripped fields and skips synthetic positions on the JVM side
    //     by counting non-synthetic predecessors;
    // (b) partition-tail indexes start at the STRIPPED data length, not the
    //     un-stripped length, because that's what native sees on the wire.
    // Without (b), a non-synthetic data column followed by a synthetic
    // (e.g. relation.dataSchema = [id, __delta_internal_is_row_deleted] on
    // a DV-rewritten Delta CDC scan) makes partition indexes overshoot the
    // native schema length, panicking `ProjectionExprs::from_indices`.
    // Consistent with `isSynthetic`: materialised row-tracking columns are data
    // columns (in fileDataSchemaFields), so they must NOT be filtered out here --
    // otherwise the projection vector wouldn't map them to the parquet read.
    val isSyntheticFieldName = (name: String) => {
      syntheticNames.contains(name.toLowerCase(Locale.ROOT))
    }
    val nonSyntheticDataIdxByName: Map[String, Int] =
      fileDataSchemaFields
        .filterNot(f => needsSyntheticEmit && isSyntheticFieldName(f.name))
        .zipWithIndex
        .map { case (f, i) => f.name.toLowerCase(Locale.ROOT) -> i }
        .toMap
    val nonSyntheticDataLen = nonSyntheticDataIdxByName.size
    val requiredIndexes: Seq[Int] = scan.requiredSchema.fields.flatMap { field =>
      if (needsSyntheticEmit && isSynthetic(field)) None
      else {
        val nameLower = field.name.toLowerCase(Locale.ROOT)
        nonSyntheticDataIdxByName.get(nameLower) match {
          case Some(idx) => Some(idx)
          case None =>
            partitionNameToIndex.get(nameLower).map(p => nonSyntheticDataLen + p)
        }
      }
    }.toSeq
    val partitionTailIndexes: Seq[Int] =
      relation.partitionSchema.fields.indices.map(i => nonSyntheticDataLen + i)
    val projectionVector: Seq[Int] = requiredIndexes ++ partitionTailIndexes
    commonBuilder.addAllProjectionVector(
      projectionVector.map(idx => idx.toLong.asInstanceOf[java.lang.Long]).toIterable.asJava)

    // Pushed-down data filters, gated by Spark's parquet filter pushdown config (same as
    // CometNativeScan). See `addPushedDataFilters`.
    addPushedDataFilters(commonBuilder, scan, syntheticNames)

    storageOptions.asScala.foreach { case (key, value) =>
      commonBuilder.putObjectStoreOptions(key, value)
    }

    // Phase 4: pass column mapping from kernel through to the native planner.
    val columnMappings = taskList.getColumnMappingsList.asScala
    columnMappings.foreach { cm =>
      commonBuilder.addColumnMappings(
        OperatorOuterClass.DeltaColumnMapping
          .newBuilder()
          .setLogicalName(cm.getLogicalName)
          .setPhysicalName(cm.getPhysicalName)
          .build())
    }

    // --- 3. Pack into a DeltaScan with COMMON ONLY (split-mode, Phase 5).
    // Tasks are NOT included in the proto at planning time. They'll be
    // serialized per-partition in CometDeltaNativeScanExec.serializedPartitionData
    // at execution time, and merged via DeltaPlanDataInjector.
    val deltaScanBuilder = DeltaScan.newBuilder()
    deltaScanBuilder.setCommon(commonBuilder.build())
    // table_root is also threaded into each per-partition DeltaScan in
    // CometDeltaNativeScanExec.packTasks; set it here as well so the planning-time
    // proto carries it for any consumer that reads the parent DeltaScan directly.
    val plannedTableRoot = taskList.getTableRoot
    if (plannedTableRoot != null && plannedTableRoot.nonEmpty) {
      deltaScanBuilder.setTableRoot(plannedTableRoot)
    }
    // No addAllTasks: tasks stay in taskListBytes for the exec's lazy split.

    // Stash the full task-list bytes for createExec to retrieve. The ThreadLocal
    // bridges the convert() -> createExec() gap in CometExecRule.convertToComet.
    // Build a modified taskList with ONLY the filtered tasks (partition-pruned).
    val filteredTaskList = DeltaScanTaskList
      .newBuilder()
      .setSnapshotVersion(taskList.getSnapshotVersion)
      .setTableRoot(taskList.getTableRoot)
      .addAllTasks(filteredTasks.asJava)
      .addAllColumnMappings(taskList.getColumnMappingsList)
      .addAllUnsupportedFeatures(taskList.getUnsupportedFeaturesList)
      .build()
    lastTaskListBytes.set(filteredTaskList.toByteArray)

    // Use the typed DeltaScan proto variant. Core's planner dispatches via the
    // OpStruct::DeltaScan match arm under `#[cfg(feature = "contrib-delta")]`.
    builder.clearChildren()
    Some(builder.setDeltaScan(deltaScanBuilder.build()).build())
  }

  /**
   * Serialize the scan's supported data filters into a single predicate proto for kernel's
   * stats-based file pruning during log replay (the same filters are also pushed into
   * ParquetSource separately, see `addPushedDataFilters` -- the two layers are additive).
   *
   * All supported filters are combined into one AND conjunction. `BoundReference`s carry the
   * column INDEX into `scan.output`; the native side resolves indices to column names via the
   * `columnNames` array passed alongside. Returns an empty array when no filter serializes.
   */
  private def serializeSupportedDataFilters(scan: CometDeltaScanMarker): Array[Byte] = {
    val protoFilters = new ListBuffer[Expr]()
    scan.supportedDataFilters.foreach { filter =>
      exprToProto(filter, scan.output) match {
        case Some(proto) => protoFilters += proto
        case _ =>
      }
    }
    if (protoFilters.isEmpty) {
      Array.emptyByteArray
    } else if (protoFilters.size == 1) {
      protoFilters.head.toByteArray
    } else {
      // Combine filters into a balanced AND tree (depth O(log N) instead of
      // O(N)). A linear left-deep fold overflows protobuf's default 100-level
      // recursion limit for plans with many ANDed conditions (Delta data
      // skipping predicates routinely build deep stats expressions: e.g.
      // DataSkippingDeltaTests "remove redundant stats column references").
      // Both the JVM serde (CometNativeColumnarToRowExec re-parses the plan
      // for explain output) and the Rust prost decoder are subject to that
      // limit, so balancing the tree fixes both sides.
      def balancedAnd(slice: IndexedSeq[Expr]): Expr = {
        if (slice.size == 1) {
          slice.head
        } else {
          val mid = slice.size / 2
          val left = balancedAnd(slice.slice(0, mid))
          val right = balancedAnd(slice.slice(mid, slice.size))
          val and = ExprOuterClass.BinaryExpr
            .newBuilder()
            .setLeft(left)
            .setRight(right)
            .build()
          Expr.newBuilder().setAnd(and).build()
        }
      }
      balancedAnd(protoFilters.toIndexedSeq).toByteArray
    }
  }

  /**
   * Resolve the cloud storage options handed to kernel's `DefaultEngine` and the native parquet
   * reader. Kernel picks up `aws_*` / `azure_*` keys; anything else is ignored on the native side
   * (for now).
   *
   * We key off the table root URI rather than `inputFiles.head` because data file names can
   * contain characters that aren't URI-safe when Spark's test harness injects prefixes like
   * `test%file%prefix-` (breaks `java.net.URI.create`). The table root string comes straight from
   * `HadoopFsRelation.location.rootPaths.head.toUri` inside `DeltaReflection.extractTableRoot`, so
   * it's already properly encoded. Storage options are bucket-level anyway -- any file under the
   * same root resolves to the same config.
   *
   * For s3/s3a tables we resolve Hadoop's credential provider chain here so log replay
   * authenticates under SimpleAWSCredentialsProvider / TemporaryAWSCredentialsProvider /
   * AssumedRoleCredentialProvider / IAMInstanceCredentialsProvider just like the data path does.
   * The contrib's native engine (delta-kernel-rs's DefaultEngine backed by object_store_kernel)
   * doesn't run core's `build_credential_provider`, so we feed it resolved static keys instead.
   * SNAPSHOT resolution: log replay completes in seconds, well within any reasonable credential
   * TTL.
   */
  private def resolveStorageOptions(
      scan: CometDeltaScanMarker,
      tableRoot: String): java.util.Map[String, String] = {
    val relation = scan.relation
    val hadoopConf =
      relation.sparkSession.sessionState.newHadoopConfWithOptions(relation.options)
    val tableRootUri = java.net.URI.create(tableRoot)
    val baseOptions: Map[String, String] =
      NativeConfig.extractObjectStoreOptions(hadoopConf, tableRootUri)
    CometDeltaNativeScan
      .augmentWithResolvedAwsCredentials(baseOptions, tableRootUri, hadoopConf)
      .asJava
  }

  /**
   * Compute the `final_output_indices` reorder map: for each `required_schema` position, the
   * index into the wrapped exec's output (parquet output columns followed by appended synthetics
   * in canonical emit order). The native dispatcher applies a final ProjectionExec to reorder
   * columns to match Spark's expected layout. Returns `Seq.empty` when no reorder is needed --
   * either no synthetics are emitted, or they already form a correctly-ordered contiguous suffix
   * of `required_schema`.
   */
  private def computeFinalOutputIndices(
      needsSyntheticEmit: Boolean,
      requiredSchemaForProto: Array[StructField],
      isSynthetic: StructField => Boolean,
      emitRowIndex: Boolean,
      emitIsRowDeleted: Boolean,
      emitRowId: Boolean,
      emitRowCommitVersion: Boolean,
      rowIndexColumnAlias: String,
      metadataColumnNamesEmitted: Seq[String]): Seq[Int] = if (!needsSyntheticEmit) Seq.empty
  else {
    val firstSyntheticIdx = requiredSchemaForProto.indexWhere(isSynthetic)
    val syntheticContiguousSuffix = firstSyntheticIdx >= 0 &&
      requiredSchemaForProto.drop(firstSyntheticIdx).forall(isSynthetic)
    // Synthetic suffix is necessary but NOT sufficient: the order of synthetics
    // within the suffix must also match the canonical emission order
    // (row_index, is_row_deleted, row_id, row_commit_version, then metadata names
    // in `metadataColumnNamesEmitted` order). When the upstream Filter / Project
    // binds attributes by ordinal (Delta's PreprocessTableWithDVs adds
    // `Filter(__delta_internal_is_row_deleted = 0)` directly above the scan),
    // an order mismatch silently misreads one synthetic as another. Force a
    // reorder Projection in that case.
    val canonicalSyntheticEmitOrder: Seq[String] = (Seq(
      (emitRowIndex,
        (if (rowIndexColumnAlias.nonEmpty) rowIndexColumnAlias
         else DeltaReflection.RowIndexColumnName).toLowerCase(Locale.ROOT)),
      (emitIsRowDeleted,
        DeltaReflection.IsRowDeletedColumnName.toLowerCase(Locale.ROOT)),
      (emitRowId, DeltaReflection.RowIdColumnName.toLowerCase(Locale.ROOT)),
      (emitRowCommitVersion,
        DeltaReflection.RowCommitVersionColumnName.toLowerCase(Locale.ROOT))).collect {
      case (true, name) => name
    }) ++ metadataColumnNamesEmitted
    val suffixSyntheticNames = requiredSchemaForProto
      .drop(firstSyntheticIdx)
      .map(_.name.toLowerCase(Locale.ROOT))
      .toSeq
    val syntheticSuffixOrderMatches =
      syntheticContiguousSuffix && suffixSyntheticNames == canonicalSyntheticEmitOrder
    if (syntheticSuffixOrderMatches) Seq.empty
    else {
      // Native synthetic emit order in build_output_schema (synthetic_columns.rs):
      // row_index, is_row_deleted, row_id, row_commit_version, then any
      // metadata_column_names in the order they were added. Use the row_index
      // ALIAS name when set (e.g. `_tmp_metadata_row_index`) so emit-order
      // lookup matches what's in required_schema.
      val rowIndexEmittedName =
        if (rowIndexColumnAlias.nonEmpty) rowIndexColumnAlias
        else DeltaReflection.RowIndexColumnName
      val syntheticEmitOrder: Seq[String] = (Seq(
        (emitRowIndex, rowIndexEmittedName),
        (emitIsRowDeleted, DeltaReflection.IsRowDeletedColumnName),
        (emitRowId, DeltaReflection.RowIdColumnName),
        (emitRowCommitVersion, DeltaReflection.RowCommitVersionColumnName)).collect {
        case (true, name) => name.toLowerCase(Locale.ROOT)
      }) ++ metadataColumnNamesEmitted
      val nonSyntheticFields = requiredSchemaForProto.filterNot(isSynthetic)
      val nonSyntheticIdxByName: Map[String, Int] =
        nonSyntheticFields.zipWithIndex.map { case (f, i) =>
          f.name.toLowerCase(Locale.ROOT) -> i
        }.toMap
      val syntheticTailStart = nonSyntheticFields.length
      requiredSchemaForProto.map { f =>
        val name = f.name.toLowerCase(Locale.ROOT)
        if (isSynthetic(f)) {
          val emitIdx = syntheticEmitOrder.indexOf(name)
          // emit flags are derived from the same scan.requiredSchema field names
          // (lines above), so any synthetic field here must have its corresponding
          // emit flag on -- a mismatch would indicate a user column collided with a
          // reserved synthetic name AND we missed it.
          assert(
            emitIdx >= 0,
            s"synthetic column '$name' in required_schema but no emit flag is set " +
              s"(emit order: $syntheticEmitOrder)")
          syntheticTailStart + emitIdx
        } else {
          nonSyntheticIdxByName(name)
        }
      }.toSeq
    }
  }

  /**
   * Serialize the scan's supported data filters that are safe to push into ParquetSource for
   * row-group-level pruning, adding them to `commonBuilder`. Gated by Spark's parquet filter
   * pushdown config (same as CometNativeScan). Filters referencing nested struct/array/map
   * access, partition columns, or synthetic columns are skipped (see inline comments); they
   * remain correct because Spark evaluates them post-scan.
   */
  private def addPushedDataFilters(
      commonBuilder: DeltaScanCommon.Builder,
      scan: CometDeltaScanMarker,
      syntheticNames: Set[String]): Unit = {
    if (!(scan.conf.getConf(SQLConf.PARQUET_FILTER_PUSHDOWN_ENABLED) &&
        CometConf.COMET_RESPECT_PARQUET_FILTER_PUSHDOWN.get(scan.conf))) {
      return
    }
    val relation = scan.relation
    val isSynthetic = (f: StructField) => syntheticNames.contains(f.name.toLowerCase(Locale.ROOT))
    // Filters referencing nested (struct/array/map) columns aren't safe to push into
    // `ParquetSource`: DataFusion currently produces "Invalid comparison operation: Utf8 <=
    // Int32" (or similar) when the filter references an array element through
    // `GetArrayItem`/`GetStructField`/`GetMapValue`, because the expression tree is walked
    // against the file schema where the child types don't match the literal. The filter is
    // still evaluated correctly by Spark post-scan, so dropping it from pushdown keeps the
    // scan results correct at the cost of some row-group-level pruning.
    def referencesNestedAccess(e: Expression): Boolean = e.exists {
      case _: org.apache.spark.sql.catalyst.expressions.GetArrayItem => true
      case _: org.apache.spark.sql.catalyst.expressions.GetArrayStructFields => true
      case _: org.apache.spark.sql.catalyst.expressions.GetMapValue => true
      case _ => false
    }
    // Partition columns are NOT in the file's data schema; the native parquet path
    // evaluates pushed-down filters against the file-data schema only, so a filter
    // that references a partition column would resolve to an out-of-bounds Bound
    // index ("Column index N is out of bound. Schema: Field {<file-data-fields>}").
    // Spark normally separates `partitionFilters` from `dataFilters` at planning
    // time, but `scan.supportedDataFilters` can still surface filters that touch
    // both data + partition columns (or pure-partition filters when the optimizer
    // didn't peel them off cleanly). Skip any filter that references a partition
    // attribute; partition pruning is handled separately by `prunePartitions`
    // driver-side via the kernel/AddFile path.
    val partitionNamesLc: Set[String] =
      relation.partitionSchema.fields.map(_.name.toLowerCase(Locale.ROOT)).toSet
    def referencesPartitionColumn(e: Expression): Boolean = e.exists {
      case a: org.apache.spark.sql.catalyst.expressions.AttributeReference =>
        partitionNamesLc.contains(a.name.toLowerCase(Locale.ROOT))
      case _ => false
    }
    val dataFilters = new ListBuffer[Expr]()
    // Filters bind by position into the schema we hand to exprToProto. The native
    // scan's `required_schema` strips synthetic emit columns -- it's just the
    // non-synthetic, non-metadata data fields. Bind against that same layout so
    // Bound indices line up; binding against `scan.output` (which carries appended
    // _metadata.* attributes) would silently misalign whenever the prefix doesn't
    // match.
    val filterBindingInputs: Seq[org.apache.spark.sql.catalyst.expressions.Attribute] =
      scan.requiredSchema.fields.collect {
        case f if !isSynthetic(f) =>
          scan.output.find(_.name.equalsIgnoreCase(f.name)).orNull
      }.filter(_ != null).toSeq
    // Skip filters that reference any synthetic column (`__delta_internal_*`,
    // `_tmp_metadata_row_index`, `_metadata.*`, row-tracking helpers, ...). They
    // aren't present in the parquet file so the pushed-down evaluation would
    // either error out ("column N out of bounds") or, worse, evaluate against
    // unrelated parquet stats and prune rows incorrectly. Spark / Delta's Filter
    // above the scan handles them after the synthetic exec emits them.
    def referencesSyntheticColumn(e: Expression): Boolean = e.exists {
      case a: org.apache.spark.sql.catalyst.expressions.AttributeReference =>
        val lc = a.name.toLowerCase(Locale.ROOT)
        syntheticNames.contains(lc) ||
          lc.startsWith("_row-id-col-") ||
          lc.startsWith("_row-commit-version-col-")
      case _ => false
    }
    scan.supportedDataFilters.foreach { filter =>
      if (referencesNestedAccess(filter)) {
        logInfo(s"CometDeltaNativeScan: skipping pushdown of nested-access filter $filter")
      } else if (referencesPartitionColumn(filter)) {
        logInfo(s"CometDeltaNativeScan: skipping pushdown of partition-column filter $filter")
      } else if (referencesSyntheticColumn(filter)) {
        logInfo(s"CometDeltaNativeScan: skipping pushdown of synthetic-column filter $filter")
      } else {
        exprToProto(filter, filterBindingInputs) match {
          case Some(proto) => dataFilters += proto
          case _ => logWarning(s"CometDeltaNativeScan: unsupported data filter $filter")
        }
      }
    }
    commonBuilder.addAllDataFilters(dataFilters.asJava)
  }

  /**
   * Filter `tasks` down to the subset whose partition values satisfy Spark's
   * `scan.partitionFilters`. Returns the original list unchanged when the scan has no partition
   * filters.
   *
   * Recursively rewrite a `StructField` and its `DataType` so every field name at every level of
   * nesting reflects the column-mapping physical name stored in its metadata. For fields without
   * the physical-name metadata (e.g. partition columns, or inner struct fields on a
   * non-column-mapped table), the logical name is retained. Only reached for nested struct/map/
   * array elements -- top-level columns keep their logical name (the native planner does that
   * substitution via the `column_mappings` proto).
   */
  private def physicaliseStructField(f: StructField): StructField = {
    val physName =
      if (f.metadata.contains(DeltaReflection.PhysicalNameMetadataKey)) {
        f.metadata.getString(DeltaReflection.PhysicalNameMetadataKey)
      } else {
        f.name
      }
    StructField(physName, physicaliseDataType(f.dataType), f.nullable, f.metadata)
  }

  private def physicaliseDataType(dt: DataType): DataType = dt match {
    case s: StructType => StructType(s.fields.map(physicaliseStructField))
    case a: ArrayType => ArrayType(physicaliseDataType(a.elementType), a.containsNull)
    case m: MapType =>
      MapType(
        physicaliseDataType(m.keyType),
        physicaliseDataType(m.valueType),
        m.valueContainsNull)
    case other => other
  }

  /**
   * Compute Spark's `maxSplitBytes` for a Delta scan. Mirrors
   * `org.apache.spark.sql.execution.datasources.FilePartition.maxSplitBytes` verbatim so a
   * Delta-native scan splits files the same way a vanilla `FileSourceScanExec` would. Inputs are
   * file sizes (bytes); other knobs come from session conf and the relation's spark session.
   */
  private def maxSplitBytes(scan: CometDeltaScanMarker, fileSizes: Seq[Long]): Long = {
    val sparkSession = scan.relation.sparkSession
    val conf = sparkSession.sessionState.conf
    val openCostInBytes = conf.filesOpenCostInBytes
    val maxPartitionBytes = conf.filesMaxPartitionBytes
    val minPartitionNum = conf.filesMinPartitionNum
      .getOrElse(sparkSession.sparkContext.defaultParallelism)
    val totalBytes = fileSizes.map(_ + openCostInBytes).sum
    val bytesPerCore = totalBytes / math.max(1, minPartitionNum)
    math.min(maxPartitionBytes, math.max(openCostInBytes, bytesPerCore))
  }

  /**
   * Expand `tasks` so any task whose file is larger than `maxSplitBytes` is replaced by a
   * sequence of byte-range chunks. Each chunk inherits the task's metadata (partition values, DV
   * row indexes, row-tracking ids) but carries `byte_range_start` / `byte_range_end` so the
   * native parquet reader only materialises row groups whose start offset falls in this range.
   *
   * Tasks that fit in one chunk are emitted unchanged (no range fields), which preserves the
   * original whole-file semantics on the native side.
   *
   * Note on DV semantics: deletion-vector indexes on the proto are absolute row positions within
   * the file. They are copied to every chunk; the native scan filters out rows whose absolute
   * index is in the DV regardless of which chunk produced them, so duplicating the index list
   * across chunks is correct (just slightly wasteful).
   */
  private def splitTasks(
      scan: CometDeltaScanMarker,
      tasks: Seq[OperatorOuterClass.DeltaScanTask]): Seq[OperatorOuterClass.DeltaScanTask] = {
    if (tasks.isEmpty) return tasks
    // When the scan needs one task per partition (per-file `_metadata.file_path`), keep each
    // task 1:1 with a file: byte-range chunking would create multiple tasks for one file which,
    // combined with packTasks below, could end up with multiple FILES per partition and drop
    // the 2nd+ files' rows.
    if (scanNeedsOneTaskPerPartition(scan)) return tasks
    val sizes = tasks.map(_.getFileSize)
    val msb = maxSplitBytes(scan, sizes)
    if (msb <= 0) return tasks
    tasks.flatMap { task =>
      val size = task.getFileSize
      if (size <= msb) Seq(task)
      else {
        val chunks = scala.collection.mutable.ArrayBuffer[OperatorOuterClass.DeltaScanTask]()
        var offset = 0L
        while (offset < size) {
          val end = math.min(offset + msb, size)
          chunks += task.toBuilder
            .setByteRangeStart(offset)
            .setByteRangeEnd(end)
            .build()
          offset = end
        }
        chunks.toSeq
      }
    }
  }

  private def prunePartitions(
      tasks: Seq[OperatorOuterClass.DeltaScanTask],
      scan: CometDeltaScanMarker,
      partitionSchema: StructType): Seq[OperatorOuterClass.DeltaScanTask] = {
    if (scan.partitionFilters.isEmpty || partitionSchema.isEmpty) return tasks

    // Phase 5b: filter out DPP expressions (DynamicPruningExpression wrapping
    // InSubqueryExec) because they aren't resolved at planning time. Spark
    // applies them post-scan at runtime. Static partition filters are still
    // evaluated here for file-level pruning.
    val staticFilters = scan.partitionFilters.filterNot(
      _.exists(_.isInstanceOf[org.apache.spark.sql.catalyst.expressions.PlanExpression[_]]))
    if (staticFilters.isEmpty) return tasks

    // Build an `InterpretedPredicate` that expects a row whose schema matches
    // `partitionSchema`. Rewrite attribute references to `BoundReference`s keyed by
    // partition-schema field index, respecting case sensitivity.
    val caseSensitive = scan.conf.getConf[Boolean](SQLConf.CASE_SENSITIVE)
    val combined = staticFilters.reduce(And)
    val bound = combined.transform {
      case a: org.apache.spark.sql.catalyst.expressions.AttributeReference =>
        val idx = if (caseSensitive) {
          partitionSchema.fieldIndex(a.name)
        } else {
          partitionSchema.fields.indexWhere(
            _.name.toLowerCase(Locale.ROOT) == a.name.toLowerCase(Locale.ROOT))
        }
        if (idx < 0) return tasks // Can't resolve; skip pruning
        BoundReference(idx, partitionSchema(idx).dataType, partitionSchema(idx).nullable)
    }
    val predicate = InterpretedPredicate(bound)
    predicate.initialize(0)

    val sessionZoneId = java.time.ZoneId.of(scan.conf.sessionLocalTimeZone)
    tasks.filter { task =>
      val row = InternalRow.fromSeq(partitionSchema.fields.toSeq.map { field =>
        val proto = task.getPartitionValuesList.asScala.find(_.getName == field.name)
        val strValue =
          if (proto.exists(_.hasValue)) Some(proto.get.getValue) else None
        DeltaReflection.castPartitionString(strValue, field.dataType, sessionZoneId)
      })
      predicate.eval(row)
    }
  }

  /**
   * Build a kernel-independent `DeltaScanTaskList` from a caller-provided AddFile list. Used when
   * the Delta scan has a pre-materialized FileIndex (streaming micro-batch, MERGE/UPDATE/DELETE
   * post-join) so we can honour its exact file list instead of re-running log replay (which would
   * return a different set).
   *
   * Each AddFile becomes one `DeltaScanTask`. Absolute path resolution mirrors
   * `DeltaFileOperations.absolutePath`: if `AddFile.path` is already absolute (has a URI scheme),
   * keep it verbatim; otherwise join against `tableRoot`.
   */
  private def buildTaskListFromAddFiles(
      tableRoot: String,
      snapshotVersion: Long,
      addFiles: Seq[DeltaReflection.ExtractedAddFile],
      nativeOp: AnyRef,
      columnNames: Array[String],
      physicalToLogicalPartitionNames: Map[String, String] = Map.empty)
      : OperatorOuterClass.DeltaScanTaskList = {
    val tlBuilder = OperatorOuterClass.DeltaScanTaskList.newBuilder()
    tlBuilder.setTableRoot(tableRoot)
    if (snapshotVersion >= 0) tlBuilder.setSnapshotVersion(snapshotVersion)

    addFiles.foreach { af =>
      val absPath =
        if (af.path.contains(":/")) af.path
        else {
          val sep = if (tableRoot.endsWith("/")) "" else "/"
          tableRoot + sep + af.path
        }
      val taskBuilder = OperatorOuterClass.DeltaScanTask.newBuilder()
      taskBuilder.setFilePath(absPath)
      taskBuilder.setFileSize(af.size)
      DeltaReflection.parseNumRecords(af.statsJson).foreach(taskBuilder.setRecordCount)
      af.partitionValues.foreach { case (k, v) =>
        // Under column mapping, Delta stores partition values keyed by the
        // PHYSICAL column name (e.g. `col-<uuid>-part`). Our partition_schema
        // on the wire uses LOGICAL names, and `build_delta_partitioned_files`
        // native-side matches by name. Translate when we have a physical
        // ->logical map (the kernel-path jni.rs already performs the same
        // translation for its own extraction).
        val logicalName = physicalToLogicalPartitionNames.getOrElse(k, k)
        val pvBuilder =
          OperatorOuterClass.DeltaPartitionValue.newBuilder().setName(logicalName)
        if (v != null) pvBuilder.setValue(v)
        taskBuilder.addPartitionValues(pvBuilder.build())
      }
      af.baseRowId.foreach(taskBuilder.setBaseRowId)
      af.defaultRowCommitVersion.foreach(taskBuilder.setDefaultRowCommitVersion)
      af.modificationTime.foreach(taskBuilder.setModificationTime)
      // Ship the DV descriptor (KB-scale) instead of the materialised row-index
      // list (was up to 1 GB per file -- the #218 dominator). Executor decodes
      // via dv_reader::read_dv_indexes on first poll of the DV-bearing partition.
      if (af.hasDeletionVector) {
        // Pass tableRoot so addFileDvToProto can pre-resolve "u" -> "p" via Delta's
        // own absolutePath (handles Delta's test-only filename prefix; see helper).
        DeltaReflection.addFileDvToProto(af.dvDescriptor, tableRoot)
          .foreach(taskBuilder.setDv)
      }
      tlBuilder.addTasks(taskBuilder.build())
    }
    tlBuilder.build()
  }

  def createExec(nativeOp: Operator, op: CometDeltaScanMarker): CometNativeExec = {
    val tableRoot = DeltaReflection.extractTableRoot(op.relation).getOrElse("unknown")
    val tlBytes =
      try {
        Option(lastTaskListBytes.get()).getOrElse(Array.emptyByteArray)
      } finally {
        lastTaskListBytes.remove()
      }
    // Force one file per Spark partition when the scan reads MATERIALISED row-tracking
    // columns (`_row-id-col-*` / `_row-commit-version-col-*`). These are real parquet
    // columns present only in files rewritten by a row-id-preserving operation
    // (OPTIMIZE/UPDATE/MERGE) -- and ABSENT from freshly-appended/inserted files. When a
    // single Spark partition packs several such files, `core_glue` emits one parquet
    // file-group per file (needed for per-file row_index); reading a column that is
    // physically absent from some of those files across the concurrently-executed
    // file-groups non-deterministically drops whole file-groups' rows. Pinning one file
    // per partition keeps each native plan single-file-group, so the absent-column
    // null-fill happens without cross-file-group concurrency. (Same mechanism used for
    // per-file `_metadata.file_path`.) See CometDeltaRowTrackingMergeReproSuite.
    val readsMaterializedRowTracking =
      op.requiredSchema.fields.exists(f =>
        CometDeltaNativeScan.isMaterializedRowTrackingName(f.name))
    val oneTaskPerPartition = scanNeedsOneTaskPerPartition(op) || readsMaterializedRowTracking ||
      CometDeltaNativeScan.needsPerFileGroups(op)

    val dppFilters = op.partitionFilters.filter(
      _.exists(_.isInstanceOf[org.apache.spark.sql.catalyst.expressions.PlanExpression[_]]))
    val partitionSchema = op.relation.partitionSchema

    val exec = CometDeltaNativeScanExec(
      nativeOp,
      op.output,
      org.apache.spark.sql.comet.SerializedPlan(None),
      op.wrapped,
      tableRoot,
      tlBytes,
      dppFilters,
      partitionSchema,
      oneTaskPerPartition = oneTaskPerPartition)
    // `op.wrapped` (== exec.originalPlan) is the original, link-bearing scan (preserved through
    // DeltaScanRule's rebuild), so CometExecRule's "set up logical links" pass -- which keys off
    // originalPlan.logicalLink -- finds it and sets the exec's link, satisfying AQE's
    // setLogicalLinkForNewQueryStage assertion. Set it here too for good measure.
    op.wrapped.logicalLink.foreach(exec.setLogicalLink)
    exec
  }
}
